// lib/words_26_30.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_26_30: Word[] = [
  { kanji: "枝", hiragana: "えだ", meaning: "가지, 나뭇가지" },
  { kanji: "怖い", hiragana: "こわい", meaning: "무섭다, 두렵다" },
  { kanji: "稜", hiragana: "そば", meaning: "귀퉁이, 모서리" },
  { kanji: "気に入る", hiragana: "きにいる", meaning: "마음에 들다" },
  { kanji: "竹", hiragana: "たけ", meaning: "대나무" },
  { kanji: "落し物", hiragana: "おとしもの", meaning: "분실물" },
  { kanji: "米", hiragana: "こめ", meaning: "쌀" },
  { kanji: "つまらない", hiragana: "", meaning: "재미없다, 하찮다, 시시하다, 보람이 없다" },
  { kanji: "拾う", hiragana: "ひろう", meaning: "줍다" },
  { kanji: "吹く", hiragana: "ふく", meaning: "불다" },
  { kanji: "法律", hiragana: "ほうりつ", meaning: "법률" },
  { kanji: "曇り", hiragana: "くもり", meaning: "흐림" },
  { kanji: "続ける", hiragana: "つづける", meaning: "계속하다" },
  { kanji: "塵", hiragana: "ごみ", meaning: "쓰레기" },
  { kanji: "ガソリンスタンド", hiragana: "", meaning: "주유소" },
  { kanji: "丁度", hiragana: "ちょうど", meaning: "꼭, 정확히, 마치, 마침, 알맞게" },
  { kanji: "脱ぐ", hiragana: "ぬぐ", meaning: "벗다" },
  { kanji: "林", hiragana: "はやし", meaning: "숲" },
  { kanji: "剃る", hiragana: "そる", meaning: "깎다, 면도하다" },
  { kanji: "手伝う", hiragana: "てつだう", meaning: "돕다" },
  { kanji: "なるほど", hiragana: "", meaning: "정말, 과연" },
  { kanji: "質問", hiragana: "しつもん", meaning: "질문" },
  { kanji: "桜", hiragana: "さくら", meaning: "벚꽃" },
  { kanji: "一生懸命", hiragana: "いっしょうけんめい", meaning: "목숨 걸고 일을 함, 매우 열심히 함" },
  { kanji: "髭", hiragana: "ひげ", meaning: "수염" },
  { kanji: "決める", hiragana: "きめる", meaning: "정하다, 결정하다" },
  { kanji: "セット", hiragana: "", meaning: "세트, 설정" },
  { kanji: "熱い", hiragana: "あつい", meaning: "뜨겁다" },
  { kanji: "貿易", hiragana: "ぼうえき", meaning: "무역" },
  { kanji: "電報", hiragana: "でんぽう", meaning: "전보" },
  { kanji: "負ける", hiragana: "まける", meaning: "지다, 패하다" },
  { kanji: "階", hiragana: "かい", meaning: "층, ~층" },
  { kanji: "豚肉", hiragana: "ぶたにく", meaning: "돼지고기" },
  { kanji: "全然", hiragana: "ぜんぜん", meaning: "전혀, 온통, 모조리" },
  { kanji: "急行", hiragana: "きゅうこう", meaning: "급행" },
  { kanji: "砂", hiragana: "すな", meaning: "모래" },
  { kanji: "大人しい", hiragana: "おとなしい", meaning: "조용하다, 얌전하다, 어른스럽다" },
  { kanji: "いつか", hiragana: "", meaning: "언젠가, 조만간에" },
  { kanji: "直ぐに", hiragana: "すぐに", meaning: "곧, 즉시, 바로" },
  { kanji: "お宅", hiragana: "おたく", meaning: "댁, 당신, 남편" },
  { kanji: "結構", hiragana: "けっこう", meaning: "훌륭함, 좋음, 꽤" },
  { kanji: "市民", hiragana: "しみん", meaning: "시민" },
  { kanji: "踏む", hiragana: "ふむ", meaning: "밟다, 딛다" },
  { kanji: "易しい", hiragana: "やさしい", meaning: "쉽다" },
  { kanji: "雲", hiragana: "くも", meaning: "구름" },
  { kanji: "泊まる", hiragana: "とまる", meaning: "묵다, 숙박하다" },
  { kanji: "利用", hiragana: "りよう", meaning: "이용" },
  { kanji: "発音", hiragana: "はつおん", meaning: "발음" },
  { kanji: "盗む", hiragana: "ぬすむ", meaning: "훔치다" },
  { kanji: "ビール", hiragana: "", meaning: "맥주" },
  { kanji: "運ぶ", hiragana: "はこぶ", meaning: "운반하다, 옮기다" },
  { kanji: "冷蔵庫", hiragana: "れいぞうこ", meaning: "냉장고" },
  { kanji: "マッチ", hiragana: "", meaning: "성냥, 조화, 경기" },
  { kanji: "道具", hiragana: "どうぐ", meaning: "도구" },
  { kanji: "写す", hiragana: "うつす", meaning: "베끼다, 모사하다" },
  { kanji: "社長", hiragana: "しゃちょう", meaning: "사장" },
  { kanji: "バケツ", hiragana: "", meaning: "양동이" },
  { kanji: "足す", hiragana: "たす", meaning: "더하다, 보태다" },
  { kanji: "観光", hiragana: "かんこう", meaning: "관광" },
  { kanji: "家庭", hiragana: "かてい", meaning: "가정" },
  { kanji: "そんなに", hiragana: "", meaning: "그렇게" },
  { kanji: "美術館", hiragana: "びじゅつかん", meaning: "미술관" },
  { kanji: "神社", hiragana: "じんじゃ", meaning: "신사" },
  { kanji: "嘘", hiragana: "うそ", meaning: "거짓, 거짓말" },
  { kanji: "家内", hiragana: "かない", meaning: "아내, 집사람" },
  { kanji: "玩具", hiragana: "おもちゃ", meaning: "장난감, 완구" },
  { kanji: "本当", hiragana: "ほんとう", meaning: "진실, 정말" },
  { kanji: "力", hiragana: "ちから", meaning: "힘" },
  { kanji: "レベル", hiragana: "", meaning: "레벨, 수준, 정도" },
  { kanji: "床屋", hiragana: "とこや", meaning: "이발소" },
  { kanji: "屋上", hiragana: "おくじょう", meaning: "옥상" },
  { kanji: "店員", hiragana: "てんいん", meaning: "점원" },
  { kanji: "先輩", hiragana: "せんぱい", meaning: "선배" },
  { kanji: "妻", hiragana: "つま", meaning: "처, 아내" },
  { kanji: "びっくり", hiragana: "", meaning: "깜짝 놀람" },
];