// lib/words_11_15.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_11_15: Word[] = [
  { kanji: "空港", hiragana: "くうこう", meaning: "공항" },
  { kanji: "畳", hiragana: "たたみ", meaning: "다다미" },
  { kanji: "スリッパ", hiragana: "", meaning: "슬리퍼" },
  { kanji: "弁当", hiragana: "べんとう", meaning: "도시락" },
  { kanji: "忘れ物", hiragana: "わすれもの", meaning: "잊어버린 물건, 잃어버린 물건, 분실물" },
  { kanji: "ソフト", hiragana: "", meaning: "소프트, 부드러움, 소프트웨어" },
  { kanji: "辞典", hiragana: "じてん", meaning: "사전" },
  { kanji: "おや", hiragana: "", meaning: "어머나, 이런" },
  { kanji: "有名", hiragana: "ゆうめい", meaning: "유명" },
  { kanji: "ご馳走", hiragana: "ごちそう", meaning: "손님 대접, 진수성찬" },
  { kanji: "下着", hiragana: "したぎ", meaning: "속옷" },
  { kanji: "時代", hiragana: "じだい", meaning: "시대" },
  { kanji: "小学校", hiragana: "しょうがっこう", meaning: "초등학교" },
  { kanji: "個", hiragana: "こ", meaning: "개, ~개" },
  { kanji: "歯", hiragana: "は", meaning: "이, 이빨" },
  { kanji: "説明", hiragana: "せつめい", meaning: "설명" },
  { kanji: "直る", hiragana: "なおる", meaning: "고치다, 바로잡히다, 치료되다, 낫다" },
  { kanji: "島", hiragana: "しま", meaning: "섬" },
  { kanji: "入院", hiragana: "にゅういん", meaning: "입원" },
  { kanji: "入社", hiragana: "にゅうしゃ", meaning: "입사" },
  { kanji: "間違える", hiragana: "まちがえる", meaning: "잘못하다, 틀리다" },
  { kanji: "アフリカ", hiragana: "", meaning: "아프리카" },
  { kanji: "君", hiragana: "きみ", meaning: "자네, 너" },
  { kanji: "食事", hiragana: "しょくじ", meaning: "식사" },
  { kanji: "消しゴム", hiragana: "けしごむ", meaning: "지우개" },
  { kanji: "箱", hiragana: "はこ", meaning: "상자" },
  { kanji: "通り", hiragana: "よおり", meaning: "길, 통함, 종류, 방법" },
  { kanji: "注意", hiragana: "ちゅうい", meaning: "주의" },
  { kanji: "ひと月", hiragana: "ひとつき", meaning: "한 달, 1개월" },
  { kanji: "必要", hiragana: "ひつよう", meaning: "필요" },
  { kanji: "窺う", hiragana: "うかがう", meaning: "엿보다, 살피다, 노리다" },
  { kanji: "貰う", hiragana: "もらう", meaning: "받다" },
  { kanji: "浅い", hiragana: "あさい", meaning: "얕다" },
  { kanji: "駐車場", hiragana: "ちゅうしゃじょう", meaning: "주차장" },
  { kanji: "殆ど", hiragana: "ほとんど", meaning: "대부분, 거의, 대략" },
  { kanji: "飼う", hiragana: "かう", meaning: "기르다, 사육하다" },
  { kanji: "別れる", hiragana: "わかれる", meaning: "헤어지다, 갈라서다, 이별하다" },
  { kanji: "優しい", hiragana: "やさしい", meaning: "상냥하다, 다정하다" },
  { kanji: "紹介", hiragana: "しょうかい", meaning: "소개" },
  { kanji: "入学", hiragana: "にゅうがく", meaning: "입학" },
  { kanji: "寺", hiragana: "てら", meaning: "절, 사찰" },
  { kanji: "字", hiragana: "じ", meaning: "글자, 글씨" },
  { kanji: "下りる", hiragana: "おりる", meaning: "내리다, 내려오다" },
  { kanji: "揺れる", hiragana: "ゆれる", meaning: "흔들리다, 일렁거리다" },
  { kanji: "随分", hiragana: "ずいぶん", meaning: "대단히, 몹시, 상당히, 꽤, 충분히" },
  { kanji: "そう", hiragana: "", meaning: "그렇게, 그리, 그래, 정말" },
  { kanji: "醤油", hiragana: "しょうゆ", meaning: "간장" },
  { kanji: "酷い", hiragana: "ひどい", meaning: "심하다, 가혹하다, 모질다, 너무하다" },
  { kanji: "壊す", hiragana: "こわす", meaning: "파괴하다, 부수다, 고장내다" },
  { kanji: "最初", hiragana: "さいしょ", meaning: "최초" },
  { kanji: "はっきり", hiragana: "", meaning: "확실히, 분명히" },
  { kanji: "ご存じ", hiragana: "ごぞんじ", meaning: "알고 계심" },
  { kanji: "一杯", hiragana: "いっぱい", meaning: "가득" },
  { kanji: "記者", hiragana: "きしゃ", meaning: "기자" },
  { kanji: "中", hiragana: "ちゅう", meaning: "중, 한가운데, 속, 안" },
  { kanji: "固い", hiragana: "かたい", meaning: "단단하다, 딱딱하다" },
  { kanji: "それに", hiragana: "", meaning: "그런데도, 그러함에도, 게다가, 더욱이" },
  { kanji: "焼ける", hiragana: "やける", meaning: "타다, 구워지다" },
  { kanji: "中々", hiragana: "なかなか", meaning: "꽤, 좀처럼, 상당히" },
  { kanji: "疲れる", hiragana: "つかれる", meaning: "지치다, 피로해지다" },
  { kanji: "見物", hiragana: "けんぶつ", meaning: "구경, 볼만한 것, 볼 거리" },
  { kanji: "両方", hiragana: "りょうほう", meaning: "양방, 쌍방" },
  { kanji: "文法", hiragana: "ぶんぽう", meaning: "문법" },
  { kanji: "最近", hiragana: "さいきん", meaning: "최근" },
  { kanji: "梅雨", hiragana: "つゆ", meaning: "장마" },
  { kanji: "手元", hiragana: "てもと", meaning: "수중, 손이 미치는 범위, 자기 주위" },
  { kanji: "事務所", hiragana: "じむしょ", meaning: "사무소" },
  { kanji: "音", hiragana: "おと", meaning: "소리" },
  { kanji: "飾り", hiragana: "かざり", meaning: "꾸밈, 장식, 치장" },
  { kanji: "増える", hiragana: "ふえる", meaning: "늘다, 증가하다" },
  { kanji: "終わり", hiragana: "おわり", meaning: "끝, 마지막" },
  { kanji: "戸", hiragana: "と", meaning: "문" },
  { kanji: "生活", hiragana: "せいかつ", meaning: "생활" },
  { kanji: "此の頃", hiragana: "このごろ", meaning: "요즘, 이즘, 요 며칠" },
  { kanji: "明日", hiragana: "あす", meaning: "명일, 내일" },
];