// lib/words_21_25.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_21_25: Word[] = [
  { kanji: "側", hiragana: "がわ", meaning: "옆, 곁, 주위, 둘레, 테" },
  { kanji: "スピーチ", hiragana: "", meaning: "스피치, 연설" },
  { kanji: "可笑しい", hiragana: "おかしい", meaning: "우습다, 우스꽝스럽다, 이상하다" },
  { kanji: "進む", hiragana: "すすむ", meaning: "나아가다, 진출하다" },
  { kanji: "大分", hiragana: "だいぶ", meaning: "상당히, 꽤" },
  { kanji: "会場", hiragana: "かいじょう", meaning: "회장" },
  { kanji: "係る", hiragana: "かかる", meaning: "관계되다, 관련되다" },
  { kanji: "自転車", hiragana: "じてんしゃ", meaning: "자전거" },
  { kanji: "乾く", hiragana: "かわく", meaning: "마르다, 건조하다" },
  { kanji: "期間", hiragana: "きかん", meaning: "기간" },
  { kanji: "どんどん", hiragana: "", meaning: "점점, 자꾸, 계속" },
  { kanji: "寄る", hiragana: "よる", meaning: "접근하다, 다가가다, 들르다" },
  { kanji: "毎年", hiragana: "まいとし", meaning: "매년, 매해, 해마다" },
  { kanji: "遠く", hiragana: "とおく", meaning: "먼 곳, 멀리, 훨씬, 매우" },
  { kanji: "通う", hiragana: "かよう", meaning: "다니다, 왕래하다" },
  { kanji: "ダンス", hiragana: "", meaning: "댄스" },
  { kanji: "孫", hiragana: "まご", meaning: "손자, 손주" },
  { kanji: "復習", hiragana: "ふくしゅう", meaning: "복습" },
  { kanji: "プリント", hiragana: "", meaning: "프린트, 인쇄" },
  { kanji: "為", hiragana: "ため", meaning: "위해, 위함" },
  { kanji: "国際", hiragana: "こくさい", meaning: "국제" },
  { kanji: "匂い", hiragana: "におい", meaning: "냄새, 향내" },
  { kanji: "残る", hiragana: "のこる", meaning: "남다, 여분이 생기다" },
  { kanji: "出来る丈", hiragana: "できるだけ", meaning: "가능한 한, 되도록" },
  { kanji: "何", hiragana: "なん", meaning: "무엇" },
  { kanji: "表", hiragana: "おもて", meaning: "표면, 겉" },
  { kanji: "連絡", hiragana: "れんらく", meaning: "연락" },
  { kanji: "全部", hiragana: "ぜんぶ", meaning: "전부" },
  { kanji: "億", hiragana: "おく", meaning: "억" },
  { kanji: "会議", hiragana: "かいぎ", meaning: "회의" },
  { kanji: "形", hiragana: "かたち", meaning: "모양, 형태" },
  { kanji: "絹", hiragana: "きぬ", meaning: "명주, 비단" },
  { kanji: "着く", hiragana: "つく", meaning: "닿다, 도착하다, 붙다, 매달리다" },
  { kanji: "工場", hiragana: "こうじょう", meaning: "공장" },
  { kanji: "列車", hiragana: "れっしゃ", meaning: "열차" },
  { kanji: "転ぶ", hiragana: "ころぶ", meaning: "쓰러지다, 자빠지다, 넘어지다" },
  { kanji: "産業", hiragana: "さんぎょう", meaning: "산업" },
  { kanji: "様", hiragana: "さま", meaning: "님, ~님" },
  { kanji: "興味", hiragana: "きょうみ", meaning: "흥미" },
  { kanji: "あの", hiragana: "", meaning: "저, 저기" },
  { kanji: "育てる", hiragana: "そだてる", meaning: "키우다, 기르다, 양육하다" },
  { kanji: "光る", hiragana: "ひかる", meaning: "빛나다" },
  { kanji: "台風", hiragana: "たいふう", meaning: "태풍" },
  { kanji: "予約", hiragana: "よやく", meaning: "예약" },
  { kanji: "工事", hiragana: "こうじ", meaning: "공사" },
  { kanji: "おばさん", hiragana: "", meaning: "아주머니, 이모, 고모, 숙모" },
  { kanji: "地図", hiragana: "ちず", meaning: "지도" },
  { kanji: "練習", hiragana: "れんしゅう", meaning: "연습" },
  { kanji: "掛ける", hiragana: "かける", meaning: "걸다, 매달다, 잠그다, 채우다" },
  { kanji: "乗り換え", hiragana: "のりかえ", meaning: "갈아탐, 바꿔 탐, 환승" },
  { kanji: "倒れる", hiragana: "たおれる", meaning: "쓰러지다, 넘어지다, 무너지다" },
  { kanji: "自動車", hiragana: "じどうしゃ", meaning: "자동차" },
  { kanji: "運転手", hiragana: "うんてんしゅ", meaning: "운전수" },
  { kanji: "老人", hiragana: "ろうじん", meaning: "노인" },
  { kanji: "動物園", hiragana: "どうぶつえん", meaning: "동물원" },
  { kanji: "皆", hiragana: "みな", meaning: "다, 모두, 전부" },
  { kanji: "大事", hiragana: "だいじ", meaning: "큰일, 중요함, 소중함" },
  { kanji: "世話", hiragana: "せわ", meaning: "폐, 신세" },
  { kanji: "日", hiragana: "ひ", meaning: "해, 햇빛, 볕, 낮, ~날" },
  { kanji: "簡単", hiragana: "かんたん", meaning: "간단" },
  { kanji: "分", hiragana: "ふん", meaning: "분" },
  { kanji: "ジャム", hiragana: "", meaning: "잼" },
  { kanji: "都合", hiragana: "つごう", meaning: "형편, 사정" },
  { kanji: "丁寧", hiragana: "ていねい", meaning: "정중함, 신중함" },
  { kanji: "では", hiragana: "", meaning: "그러면, 그렇다면, 그럼" },
  { kanji: "廊下", hiragana: "ろうか", meaning: "복도" },
  { kanji: "金魚", hiragana: "きんぎょ", meaning: "금붕어" },
  { kanji: "必ず", hiragana: "かならず", meaning: "반드시, 꼭" },
  { kanji: "姉妹", hiragana: "しまい", meaning: "자매" },
  { kanji: "帽子", hiragana: "ぼうし", meaning: "모자" },
  { kanji: "飾る", hiragana: "かざる", meaning: "장식하다, 꾸미다, 치장하다" },
  { kanji: "厳しい", hiragana: "きびしい", meaning: "엄하다, 엄격하다, 심하다" },
  { kanji: "食料品", hiragana: "しょくりょうひん", meaning: "식료품" },
  { kanji: "最後", hiragana: "さいご", meaning: "최후, 마지막" },
];
