// lib/words_41_45.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_41_45: Word[] = [
  { kanji: "欲しい", hiragana: "ほしい", meaning: "가지고 싶다, 원하다, 바라다" },
  { kanji: "今回", hiragana: "こんかい", meaning: "이번 회, 이번" },
  { kanji: "安心", hiragana: "あんしん", meaning: "안심" },
  { kanji: "昼間", hiragana: "ひるま", meaning: "주간, 낮" },
  { kanji: "都", hiragana: "と", meaning: "도시, 도" },
  { kanji: "交通", hiragana: "こうつう", meaning: "교통" },
  { kanji: "無理", hiragana: "むり", meaning: "무리, 할 수 없음" },
  { kanji: "爪", hiragana: "つめ", meaning: "손톱, 발톱" },
  { kanji: "違う", hiragana: "ちがう", meaning: "다르다, 틀리다, 잘못되다" },
  { kanji: "オートバイ", hiragana: "", meaning: "오토바이" },
  { kanji: "亡くなる", hiragana: "なくなる", meaning: "죽다, 돌아가시다" },
  { kanji: "事", hiragana: "こと", meaning: "일, 것, 경우, 사항" },
  { kanji: "等", hiragana: "など", meaning: "따위, 등" },
  { kanji: "痩せる", hiragana: "やせる", meaning: "여위다, 살이 빠지다" },
  { kanji: "葉", hiragana: "は", meaning: "잎, 잎사귀" },
  { kanji: "只今", hiragana: "ただいま", meaning: "지금, 현재, 방금, 이제 막" },
  { kanji: "植える", hiragana: "うえる", meaning: "심다" },
  { kanji: "小鳥", hiragana: "ことり", meaning: "작은 새" },
  { kanji: "片付ける", hiragana: "かたづける", meaning: "치우다, 정돈하다, 정리하다" },
  { kanji: "卒業", hiragana: "そつぎょう", meaning: "졸업" },
  { kanji: "サイン", hiragana: "", meaning: "사인, 서명, 신호" },
  { kanji: "眠い", hiragana: "ねむい", meaning: "졸리다" },
  { kanji: "世界", hiragana: "せかい", meaning: "세계" },
  { kanji: "自由", hiragana: "じゆう", meaning: "자유" },
  { kanji: "砂糖", hiragana: "さとう", meaning: "설탕" },
  { kanji: "それから", hiragana: "", meaning: "그 다음에, 그리고, 그 뒤, 그 이래" },
  { kanji: "珍しい", hiragana: "めずらしい", meaning: "드물다, 희귀하다" },
  { kanji: "下げる", hiragana: "さげる", meaning: "내리다, 내려주다" },
  { kanji: "夢", hiragana: "ゆめ", meaning: "꿈" },
  { kanji: "大抵", hiragana: "たいてい", meaning: "대개, 대부분, 대체, 대충, 대강" },
  { kanji: "寝坊", hiragana: "ねぼう", meaning: "늦잠, 잠꾸러기" },
  { kanji: "指輪", hiragana: "ゆびわ", meaning: "반지" },
  { kanji: "お陰", hiragana: "おかげ", meaning: "덕, 덕택, 덕분" },
  { kanji: "下宿", hiragana: "げしゅく", meaning: "하숙, 하숙집" },
  { kanji: "閉じる", hiragana: "とじる", meaning: "닫히다, 끝나다, 닫다" },
  { kanji: "差す", hiragana: "さす", meaning: "쓰다, 꽂다" },
  { kanji: "似る", hiragana: "にる", meaning: "닮다, 비슷하다" },
  { kanji: "すると", hiragana: "", meaning: "그러자, 그랬더니, 그러면, 그렇다면" },
  { kanji: "仕舞う", hiragana: "しまう", meaning: "끝나다, 끝내다, 마치다" },
  { kanji: "酔い", hiragana: "よい", meaning: "취함, 취기, 멀미" },
  { kanji: "止める", hiragana: "とめる", meaning: "멈추다, 세우다, 정지하다, 말리다" },
  { kanji: "腕", hiragana: "うで", meaning: "팔" },
  { kanji: "熱", hiragana: "ねつ", meaning: "열" },
  { kanji: "客", hiragana: "きゃく", meaning: "손님, 여객" },
  { kanji: "試験", hiragana: "しけん", meaning: "시험" },
  { kanji: "首", hiragana: "くび", meaning: "목" },
  { kanji: "迎える", hiragana: "むかえる", meaning: "맞이하다, 맞다, 마중하다" },
  { kanji: "ステレオ", hiragana: "", meaning: "스테레오, 입체, 입체 장치" },
  { kanji: "工業", hiragana: "こうぎょう", meaning: "공업" },
  { kanji: "それほど", hiragana: "", meaning: "그렇게, 그다지, 그만큼" },
  { kanji: "建つ", hiragana: "たつ", meaning: "서다, 세워지다" },
  { kanji: "レコード", hiragana: "", meaning: "레코드, 음반, 축음기판" },
  { kanji: "地震", hiragana: "じしん", meaning: "지진" },
  { kanji: "壁", hiragana: "かべ", meaning: "벽" },
  { kanji: "僕", hiragana: "ぼく", meaning: "저, 나" },
  { kanji: "寂しい", hiragana: "さびしい", meaning: "외롭다, 쓸쓸하다" },
  { kanji: "飛行場", hiragana: "ひこうじょう", meaning: "비행장" },
  { kanji: "事故", hiragana: "じこ", meaning: "사고" },
  { kanji: "売り場", hiragana: "うりば", meaning: "매장, 파는 곳, 판매장, 매표소" },
  { kanji: "楽しみ", hiragana: "たのしみ", meaning: "즐거움, 낙, 기대" },
  { kanji: "知る", hiragana: "しる", meaning: "알다" },
  { kanji: "そして", hiragana: "", meaning: "그리고" },
  { kanji: "すっかり", hiragana: "", meaning: "죄다, 모두, 완전히, 몽땅" },
  { kanji: "本棚", hiragana: "ほんだな", meaning: "책꽂이, 책장" },
  { kanji: "頑張る", hiragana: "がんばる", meaning: "열심히 하다, 힘내다" },
  { kanji: "遠慮", hiragana: "えんりょ", meaning: "염려, 사양" },
  { kanji: "命", hiragana: "いのち", meaning: "목숨, 생명" },
  { kanji: "積もり", hiragana: "つもり", meaning: "쌓임, 어림, 견적" },
  { kanji: "涼しい", hiragana: "すずしい", meaning: "시원하다, 선선하다, 서늘하다" },
  { kanji: "大使館", hiragana: "たいしかん", meaning: "대사관" },
  { kanji: "多分", hiragana: "たぶん", meaning: "아마" },
  { kanji: "村", hiragana: "むら", meaning: "마을, 촌락" },
  { kanji: "昼休み", hiragana: "ひるやすみ", meaning: "점심 시간" },
  { kanji: "変", hiragana: "へん", meaning: "변화, 이상함" },
  { kanji: "タイプ", hiragana: "", meaning: "타입" },
];