// lib/words_31_35.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_31_35: Word[] = [
  { kanji: "夕べ", hiragana: "ゆうべ", meaning: "저녁때, 해질녁" },
  { kanji: "歌手", hiragana: "かしゅ", meaning: "가수" },
  { kanji: "歴史", hiragana: "れきし", meaning: "역사" },
  { kanji: "文学", hiragana: "ぶんがく", meaning: "문학" },
  { kanji: "ジュース", hiragana: "", meaning: "주스, 쥬스" },
  { kanji: "原因", hiragana: "げんいん", meaning: "원인" },
  { kanji: "関係", hiragana: "かんけい", meaning: "관계" },
  { kanji: "無くなる", hiragana: "なくなる", meaning: "없어지다, 죽다" },
  { kanji: "方", hiragana: "かた", meaning: "쪽, 편, 방향, 분" },
  { kanji: "会", hiragana: "かい", meaning: "모임, 회" },
  { kanji: "約束", hiragana: "やくそく", meaning: "약속" },
  { kanji: "取り替える", hiragana: "とりかえる", meaning: "갈다, 바꾸다, 교체하다, 교환하다" },
  { kanji: "私", hiragana: "わたくし", meaning: "저, 나" },
  { kanji: "アルコール", hiragana: "", meaning: "알코올" },
  { kanji: "参", hiragana: "さん", meaning: "참가, 참가함" },
  { kanji: "背", hiragana: "せ", meaning: "등, 키" },
  { kanji: "無くす", hiragana: "なくす", meaning: "잃다" },
  { kanji: "盛ん", hiragana: "さかん", meaning: "활발함, 기세 좋음, 맹렬함, 번성함" },
  { kanji: "背広", hiragana: "せびろ", meaning: "신사복" },
  { kanji: "エスカレーター", hiragana: "", meaning: "에스컬레이터" },
  { kanji: "文章", hiragana: "ぶんしょう", meaning: "문장" },
  { kanji: "騒ぐ", hiragana: "さわぐ", meaning: "떠들다, 시끄러워지다" },
  { kanji: "ピクニック", hiragana: "", meaning: "피크닉, 소풍" },
  { kanji: "さっき", hiragana: "", meaning: "아까, 조금 전" },
  { kanji: "営業", hiragana: "えいぎょう", meaning: "영업" },
  { kanji: "肩", hiragana: "かた", meaning: "어깨" },
  { kanji: "招待", hiragana: "しょうたい", meaning: "초대" },
  { kanji: "昨夜", hiragana: "ゆうべ", meaning: "어제 저녁, 어젯밤" },
  { kanji: "外国", hiragana: "がいこく", meaning: "외국" },
  { kanji: "塗る", hiragana: "ぬる", meaning: "바르다, 칠하다, 화장을 하다" },
  { kanji: "回", hiragana: "かい", meaning: "~회, ~번, 횟수" },
  { kanji: "細かい", hiragana: "こまかい", meaning: "세세하다, 상세하다, 미세하다" },
  { kanji: "止む", hiragana: "やむ", meaning: "그치다, 멈추다" },
  { kanji: "度", hiragana: "ど", meaning: "도, 정도" },
  { kanji: "主人", hiragana: "しゅじん", meaning: "주인, 업체의 임자, 일가의 가구주, 남편" },
  { kanji: "数学", hiragana: "すうがく", meaning: "수학" },
  { kanji: "厚い", hiragana: "あつい", meaning: "두껍다, 두텁다, 많다" },
  { kanji: "専門", hiragana: "せんもん", meaning: "전문" },
  { kanji: "欠席", hiragana: "けっせき", meaning: "결석" },
  { kanji: "過ぎる", hiragana: "すぎる", meaning: "지나다, 지나치다, 통과하다" },
  { kanji: "聞き取り", hiragana: "ききとり", meaning: "청취, 듣기, 사정을 들음" },
  { kanji: "住所", hiragana: "じゅうしょ", meaning: "주소" },
  { kanji: "晩", hiragana: "ばん", meaning: "밤, 저녁" },
  { kanji: "筈", hiragana: "はず", meaning: "~할 예정, ~할 리" },
  { kanji: "邪魔", hiragana: "じゃま", meaning: "방해" },
  { kanji: "海岸", hiragana: "かいがん", meaning: "해안" },
  { kanji: "引く", hiragana: "ひく", meaning: "끌다, 잡아끌다, 당기다" },
  { kanji: "鉤", hiragana: "かぎ", meaning: "갈고리" },
  { kanji: "駐車", hiragana: "ちゅうしゃ", meaning: "주차" },
  { kanji: "茶色", hiragana: "ちゃいろ", meaning: "갈색" },
  { kanji: "スーツケース", hiragana: "", meaning: "슈트케이스, 여행용 가방" },
  { kanji: "輸入", hiragana: "ゆにゅう", meaning: "수입" },
  { kanji: "政治", hiragana: "せいじ", meaning: "정치" },
  { kanji: "人口", hiragana: "じんこう", meaning: "인구" },
  { kanji: "展覧会", hiragana: "てんらんかい", meaning: "전람회" },
  { kanji: "通る", hiragana: "とおる", meaning: "통하다, 통과하다, 뚫리다, 지나다, 지나가다" },
  { kanji: "田舎", hiragana: "いなか", meaning: "시골, 지방" },
  { kanji: "算数", hiragana: "さんすう", meaning: "산수" },
  { kanji: "ワイシャツ", hiragana: "", meaning: "와이셔츠" },
  { kanji: "気", hiragana: "き", meaning: "기운, 기, 기력" },
  { kanji: "だから", hiragana: "", meaning: "그러므로, 그러니까, 그래서" },
  { kanji: "申し上げる", hiragana: "もうしあげる", meaning: "말씀드리다, 여쭈다" },
  { kanji: "ちっとも", hiragana: "", meaning: "조금도, 잠시도" },
  { kanji: "集める", hiragana: "あつめる", meaning: "모으다" },
  { kanji: "考える", hiragana: "かんがえる", meaning: "생각하다" },
  { kanji: "十", hiragana: "とお", meaning: "열, 10, 열 살" },
  { kanji: "伺う", hiragana: "うかがう", meaning: "가다, 오다, 듣다, 묻다, 방문하다" },
  { kanji: "嬉しい", hiragana: "うれしい", meaning: "기쁘다" },
  { kanji: "やはり", hiragana: "", meaning: "역시" },
  { kanji: "包む", hiragana: "つつむ", meaning: "싸다, 포장하다" },
  { kanji: "もう", hiragana: "", meaning: "벌써, 이미, 이제, 곧" },
  { kanji: "以上", hiragana: "いじょう", meaning: "이상, ~보다 많음" },
  { kanji: "十分", hiragana: "じゅうぶん", meaning: "충분" },
  { kanji: "直す", hiragana: "なおす", meaning: "고치다, 수리하다, 정정하다, 바로잡다" },
  { kanji: "コンサート", hiragana: "", meaning: "콘서트" },
];