// lib/words_01_05.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_01_05: Word[] = [
  { kanji: "漫画", hiragana: "まんが", meaning: "만화" },
  { kanji: "予習", hiragana: "よしゅう", meaning: "예습" },
  { kanji: "顎", hiragana: "あご", meaning: "턱" },
  { kanji: "訳", hiragana: "わけ", meaning: "이유, 의미, 뜻, 사정" },
  { kanji: "気分", hiragana: "きぶん", meaning: "기분" },
  { kanji: "見える", hiragana: "みえる", meaning: "보이다, 눈에 들어오다, 볼 수 있다" },
  { kanji: "祝う", hiragana: "いわう", meaning: "축하하다, 축복하다" },
  { kanji: "なる", hiragana: "", meaning: "~이 되다, 되다" },
  { kanji: "荷物", hiragana: "にもつ", meaning: "화물, 짐" },
  { kanji: "届ける", hiragana: "とどける", meaning: "보내다, 배달하다, 신고하다" },
  { kanji: "テープレコーダー", hiragana: "", meaning: "테이프 레코더, 테이프식 녹음기" },
  { kanji: "喉", hiragana: "のど", meaning: "목, 인후, 목구멍" },
  { kanji: "国民", hiragana: "こくみん", meaning: "국민" },
  { kanji: "穿く", hiragana: "はく", meaning: "입다, 신다" },
  { kanji: "交差点", hiragana: "こうさてん", meaning: "교차로, 교차점, 사거리" },
  { kanji: "キロ", hiragana: "", meaning: "킬로, km" },
  { kanji: "召し上がる", hiragana: "めしあがる", meaning: "드시다" },
  { kanji: "挨拶", hiragana: "あいさつ", meaning: "인사" },
  { kanji: "確か", hiragana: "たしか", meaning: "확실함, 틀림없음, 믿을 수 있음" },
  { kanji: "掏摸", hiragana: "すり", meaning: "소매치기" },
  { kanji: "プール", hiragana: "", meaning: "풀장, 수영장" },
  { kanji: "運", hiragana: "うん", meaning: "운, 운명, 운수" },
  { kanji: "眠る", hiragana: "ねむる", meaning: "자다, 잠자다, 잠들다" },
  { kanji: "嘴", hiragana: "はし", meaning: "부리, 주둥이" },
  { kanji: "調べる", hiragana: "しらべる", meaning: "조사하다, 알아보다, 살펴보다, 찾다, 연구하다" },
  { kanji: "変える", hiragana: "かえる", meaning: "바꾸다, 변하다" },
  { kanji: "空く", hiragana: "あく", meaning: "비다, 들어 있지 않다" },
  { kanji: "汚れる", hiragana: "よごれる", meaning: "더러워지다" },
  { kanji: "踊る", hiragana: "おどる", meaning: "춤추다" },
  { kanji: "ドラマ", hiragana: "", meaning: "드라마" },
  { kanji: "左", hiragana: "ひだり", meaning: "좌, 왼편, 왼쪽" },
  { kanji: "赤ちゃん", hiragana: "あかちゃん", meaning: "아기, 새끼" },
  { kanji: "日", hiragana: "にち", meaning: "일, 날" },
  { kanji: "忘れる", hiragana: "わすれる", meaning: "잊다, 잊어버리다" },
  { kanji: "七つ", hiragana: "ななつ", meaning: "일곱, 일곱 살, 일곱 개" },
  { kanji: "苛める", hiragana: "いじめる", meaning: "괴롭히다" },
  { kanji: "具合", hiragana: "ぐあい", meaning: "형편, 상태" },
  { kanji: "場合", hiragana: "ばあい", meaning: "경우, 상황" },
  { kanji: "集まる", hiragana: "あつまる", meaning: "모이다" },
  { kanji: "慣れる", hiragana: "なれる", meaning: "익숙해지다" },
  { kanji: "汗", hiragana: "あせ", meaning: "땀" },
  { kanji: "作品", hiragana: "さくひん", meaning: "작품" },
  { kanji: "万", hiragana: "まん", meaning: "10000, 만" },
  { kanji: "驚く", hiragana: "おどろく", meaning: "놀라다, 경악하다" },
  { kanji: "秒", hiragana: "びょう", meaning: "초" },
  { kanji: "科学", hiragana: "かがく", meaning: "과학" },
  { kanji: "背中", hiragana: "せなか", meaning: "등, 뒷면, 뒤" },
  { kanji: "辺", hiragana: "へん", meaning: "근처, 부근" },
  { kanji: "心配", hiragana: "しんぱい", meaning: "걱정, 근심" },
  { kanji: "遅れる", hiragana: "おくれる", meaning: "늦다" },
  { kanji: "円い", hiragana: "まるい", meaning: "둥글다, 원형, 구형" },
  { kanji: "参る", hiragana: "まいる", meaning: "가다, 오다" },
  { kanji: "スピーカー", hiragana: "", meaning: "스피커" },
  { kanji: "渡る", hiragana: "わたる", meaning: "건너다, 건너가다" },
  { kanji: "半", hiragana: "はん", meaning: "반, 절반" },
  { kanji: "六つ", hiragana: "むっつ", meaning: "여섯 개, 6개" },
  { kanji: "探す", hiragana: "さがす", meaning: "찾다" },
  { kanji: "氷", hiragana: "こおり", meaning: "얼음" },
  { kanji: "やっと", hiragana: "", meaning: "겨우, 가까스로, 간신히, 마침내" },
  { kanji: "線", hiragana: "せん", meaning: "선" },
  { kanji: "玄関", hiragana: "げんかん", meaning: "현관" },
  { kanji: "木綿", hiragana: "もめん", meaning: "무명, 면직물, 솜" },
  { kanji: "不便", hiragana: "ふべん", meaning: "불편" },
  { kanji: "個人", hiragana: "こじん", meaning: "개인" },
  { kanji: "居る", hiragana: "おる", meaning: "있다, 계시다" },
  { kanji: "間に合う", hiragana: "まにあう", meaning: "늦지 않다, 시간에 맞추다" },
  { kanji: "沸かす", hiragana: "わかす", meaning: "데우다, 끓이다, 열광시키다" },
  { kanji: "晴れる", hiragana: "はれる", meaning: "개다, 풀리다" },
  { kanji: "運動", hiragana: "うんどう", meaning: "운동" },
  { kanji: "正しい", hiragana: "ただしい", meaning: "옳다, 바르다, 맞다" },
  { kanji: "落ちる", hiragana: "おちる", meaning: "떨어지다, 낙하하다" },
  { kanji: "三角", hiragana: "さんかく", meaning: "삼각, 세모" },
  { kanji: "送る", hiragana: "おくる", meaning: "보내다, 부치다, 송금하다" },
  { kanji: "先ず", hiragana: "まず", meaning: "우선, 먼저, 일단" },
];
