// lib/words_all.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_all: Word[] = [
  { kanji: "漫画", hiragana: "まんが", meaning: "만화" },
  { kanji: "予習", hiragana: "よしゅう", meaning: "예습" },
  { kanji: "顎", hiragana: "あご", meaning: "턱" },
  { kanji: "訳", hiragana: "わけ", meaning: "이유, 의미, 뜻, 사정" },
  { kanji: "気分", hiragana: "きぶん", meaning: "기분" },
  { kanji: "見える", hiragana: "みえる", meaning: "보이다, 눈에 들어오다, 볼 수 있다" },
  { kanji: "祝う", hiragana: "いわう", meaning: "축하하다, 축복하다" },
  { kanji: "なる", hiragana: "", meaning: "~이 되다, 되다" },
  { kanji: "荷物", hiragana: "にもつ", meaning: "화물, 짐" },
  { kanji: "届ける", hiragana: "とどける", meaning: "보내다, 배달하다, 신고하다" },
  { kanji: "テープレコーダー", hiragana: "", meaning: "테이프 레코더, 테이프식 녹음기" },
  { kanji: "喉", hiragana: "のど", meaning: "목, 인후, 목구멍" },
  { kanji: "国民", hiragana: "こくみん", meaning: "국민" },
  { kanji: "穿く", hiragana: "はく", meaning: "입다, 신다" },
  { kanji: "交差点", hiragana: "こうさてん", meaning: "교차로, 교차점, 사거리" },
  { kanji: "キロ", hiragana: "", meaning: "킬로, km" },
  { kanji: "召し上がる", hiragana: "めしあがる", meaning: "드시다" },
  { kanji: "挨拶", hiragana: "あいさつ", meaning: "인사" },
  { kanji: "確か", hiragana: "たしか", meaning: "확실함, 틀림없음, 믿을 수 있음" },
  { kanji: "掏摸", hiragana: "すり", meaning: "소매치기" },
  { kanji: "プール", hiragana: "", meaning: "풀장, 수영장" },
  { kanji: "運", hiragana: "うん", meaning: "운, 운명, 운수" },
  { kanji: "眠る", hiragana: "ねむる", meaning: "자다, 잠자다, 잠들다" },
  { kanji: "嘴", hiragana: "はし", meaning: "부리, 주둥이" },
  { kanji: "調べる", hiragana: "しらべる", meaning: "조사하다, 알아보다, 살펴보다, 찾다, 연구하다" },
  { kanji: "変える", hiragana: "かえる", meaning: "바꾸다, 변하다" },
  { kanji: "空く", hiragana: "あく", meaning: "비다, 들어 있지 않다" },
  { kanji: "汚れる", hiragana: "よごれる", meaning: "더러워지다" },
  { kanji: "踊る", hiragana: "おどる", meaning: "춤추다" },
  { kanji: "ドラマ", hiragana: "", meaning: "드라마" },
  { kanji: "左", hiragana: "ひだり", meaning: "좌, 왼편, 왼쪽" },
  { kanji: "赤ちゃん", hiragana: "あかちゃん", meaning: "아기, 새끼" },
  { kanji: "日", hiragana: "にち", meaning: "일, 날" },
  { kanji: "忘れる", hiragana: "わすれる", meaning: "잊다, 잊어버리다" },
  { kanji: "七つ", hiragana: "ななつ", meaning: "일곱, 일곱 살, 일곱 개" },
  { kanji: "苛める", hiragana: "いじめる", meaning: "괴롭히다" },
  { kanji: "具合", hiragana: "ぐあい", meaning: "형편, 상태" },
  { kanji: "場合", hiragana: "ばあい", meaning: "경우, 상황" },
  { kanji: "集まる", hiragana: "あつまる", meaning: "모이다" },
  { kanji: "慣れる", hiragana: "なれる", meaning: "익숙해지다" },
  { kanji: "汗", hiragana: "あせ", meaning: "땀" },
  { kanji: "作品", hiragana: "さくひん", meaning: "작품" },
  { kanji: "万", hiragana: "まん", meaning: "10000, 만" },
  { kanji: "驚く", hiragana: "おどろく", meaning: "놀라다, 경악하다" },
  { kanji: "秒", hiragana: "びょう", meaning: "초" },
  { kanji: "科学", hiragana: "かがく", meaning: "과학" },
  { kanji: "背中", hiragana: "せなか", meaning: "등, 뒷면, 뒤" },
  { kanji: "辺", hiragana: "へん", meaning: "근처, 부근" },
  { kanji: "心配", hiragana: "しんぱい", meaning: "걱정, 근심" },
  { kanji: "遅れる", hiragana: "おくれる", meaning: "늦다" },
  { kanji: "円い", hiragana: "まるい", meaning: "둥글다, 원형, 구형" },
  { kanji: "参る", hiragana: "まいる", meaning: "가다, 오다" },
  { kanji: "スピーカー", hiragana: "", meaning: "스피커" },
  { kanji: "渡る", hiragana: "わたる", meaning: "건너다, 건너가다" },
  { kanji: "半", hiragana: "はん", meaning: "반, 절반" },
  { kanji: "六つ", hiragana: "むっつ", meaning: "여섯 개, 6개" },
  { kanji: "探す", hiragana: "さがす", meaning: "찾다" },
  { kanji: "氷", hiragana: "こおり", meaning: "얼음" },
  { kanji: "やっと", hiragana: "", meaning: "겨우, 가까스로, 간신히, 마침내" },
  { kanji: "線", hiragana: "せん", meaning: "선" },
  { kanji: "玄関", hiragana: "げんかん", meaning: "현관" },
  { kanji: "木綿", hiragana: "もめん", meaning: "무명, 면직물, 솜" },
  { kanji: "不便", hiragana: "ふべん", meaning: "불편" },
  { kanji: "個人", hiragana: "こじん", meaning: "개인" },
  { kanji: "居る", hiragana: "おる", meaning: "있다, 계시다" },
  { kanji: "間に合う", hiragana: "まにあう", meaning: "늦지 않다, 시간에 맞추다" },
  { kanji: "沸かす", hiragana: "わかす", meaning: "데우다, 끓이다, 열광시키다" },
  { kanji: "晴れる", hiragana: "はれる", meaning: "개다, 풀리다" },
  { kanji: "運動", hiragana: "うんどう", meaning: "운동" },
  { kanji: "正しい", hiragana: "ただしい", meaning: "옳다, 바르다, 맞다" },
  { kanji: "落ちる", hiragana: "おちる", meaning: "떨어지다, 낙하하다" },
  { kanji: "三角", hiragana: "さんかく", meaning: "삼각, 세모" },
  { kanji: "送る", hiragana: "おくる", meaning: "보내다, 부치다, 송금하다" },
  { kanji: "先ず", hiragana: "まず", meaning: "우선, 먼저, 일단" },
  { kanji: "パージ", hiragana: "", meaning: "추방, 숙청" },
  { kanji: "医学", hiragana: "いがく", meaning: "의학" },
  { kanji: "受付", hiragana: "うけつけ", meaning: "접수처" },
  { kanji: "残念", hiragana: "ざんねん", meaning: "유감스러움, 아쉬움" },
  { kanji: "複雑", hiragana: "ふくざつ", meaning: "복잡" },
  { kanji: "急ぐ", hiragana: "いそぐ", meaning: "서두르다" },
  { kanji: "守る", hiragana: "まもる", meaning: "지키다" },
  { kanji: "大変", hiragana: "たいへん", meaning: "큰일, 정말, 매우" },
  { kanji: "ケーキ", hiragana: "", meaning: "케이크" },
  { kanji: "切る", hiragana: "きる", meaning: "자르다" },
  { kanji: "さす", hiragana: "", meaning: "~시키다, 시키다" },
  { kanji: "鳴く", hiragana: "なく", meaning: "소리를 내다, 울다" },
  { kanji: "ベル", hiragana: "", meaning: "벨, 종, 방울" },
  { kanji: "苦しい", hiragana: "くるしい", meaning: "괴롭다, 고통스럽다" },
  { kanji: "意見", hiragana: "いけん", meaning: "의견" },
  { kanji: "居間", hiragana: "いま", meaning: "거실" },
  { kanji: "真ん中", hiragana: "まんなか", meaning: "한가운데, 한복판" },
  { kanji: "払う", hiragana: "はらう", meaning: "없애다, 제거하다, 털다, 털어 내다, 지불하다, 값을 치르다" },
  { kanji: "フィルム", hiragana: "", meaning: "필름" },
  { kanji: "乗り換える", hiragana: "のりかえる", meaning: "바꿔 타다, 갈아타다, 환승하다" },
  { kanji: "安全", hiragana: "あんぜん", meaning: "안전" },
  { kanji: "喜ぶ", hiragana: "よろこぶ", meaning: "기뻐하다" },
  { kanji: "付ける", hiragana: "つける", meaning: "붙이다, 달다" },
  { kanji: "即ける", hiragana: "つける", meaning: "왕위에 앉히다, 즉위하다" },
  { kanji: "しっかり", hiragana: "", meaning: "단단히, 꽉, 확고히, 제대로" },
  { kanji: "凄い", hiragana: "すごい", meaning: "굉장하다, 대단하다" },
  { kanji: "汽車", hiragana: "きしゃ", meaning: "기차" },
  { kanji: "贈り物", hiragana: "おくりもの", meaning: "선물" },
  { kanji: "人", hiragana: "にん", meaning: "사람, 인품" },
  { kanji: "映画", hiragana: "えいが", meaning: "영화" },
  { kanji: "アイロン", hiragana: "", meaning: "다리미, 헤어 아이롱, 고데기" },
  { kanji: "美しい", hiragana: "うつくしい", meaning: "아름답다, 예쁘다" },
  { kanji: "アルバイト", hiragana: "", meaning: "아르바이트" },
  { kanji: "授業", hiragana: "じゅぎょう", meaning: "수업" },
  { kanji: "届く", hiragana: "とどく", meaning: "닿다, 도달하다, 이루어지다" },
  { kanji: "外部", hiragana: "がいぶ", meaning: "외부" },
  { kanji: "勝つ", hiragana: "かつ", meaning: "이기다" },
  { kanji: "零", hiragana: "れい", meaning: "영, 0" },
  { kanji: "全国", hiragana: "ぜんこく", meaning: "전국" },
  { kanji: "良く", hiragana: "よく", meaning: "잘, 충분히, 좋게" },
  { kanji: "ぶつかる", hiragana: "", meaning: "부딪히다, 충돌하다" },
  { kanji: "謝る", hiragana: "あやまる", meaning: "사과하다" },
  { kanji: "褒める", hiragana: "ほめる", meaning: "칭찬하다" },
  { kanji: "又は", hiragana: "または", meaning: "또는, 혹은, 그게 아니면" },
  { kanji: "沸く", hiragana: "わく", meaning: "끓다, 금속이 녹다, 발효하다" },
  { kanji: "打つ", hiragana: "うつ", meaning: "치다, 때리다, 두드리다" },
  { kanji: "見付ける", hiragana: "みつける", meaning: "찾다, 발견하다" },
  { kanji: "選手", hiragana: "せんしゅ", meaning: "선수" },
  { kanji: "高校", hiragana: "こうこう", meaning: "고교, 고등학교" },
  { kanji: "カーテン", hiragana: "", meaning: "커튼" },
  { kanji: "例えば", hiragana: "たとえば", meaning: "예를 들면, 예컨대, 가령" },
  { kanji: "さあ", hiragana: "", meaning: "자, 어서, 글쎄" },
  { kanji: "釣る", hiragana: "つる", meaning: "낚다, 꾀다, 유혹하다" },
  { kanji: "鏡", hiragana: "かがみ", meaning: "거울" },
  { kanji: "逃げる", hiragana: "にげる", meaning: "도망치다, 달아나다, 회피하다" },
  { kanji: "ニュース", hiragana: "", meaning: "뉴스" },
  { kanji: "この間", hiragana: "このあいだ", meaning: "일전, 요전, 지난번" },
  { kanji: "温い", hiragana: "ぬるい", meaning: "미지근하다, 미적지근하다" },
  { kanji: "退院", hiragana: "たいいん", meaning: "퇴원" },
  { kanji: "流れる", hiragana: "ながれる", meaning: "흐르다, 흘러내리다, 흘러가다" },
  { kanji: "ワンピース", hiragana: "", meaning: "원피스" },
  { kanji: "西洋", hiragana: "せいよう", meaning: "서양" },
  { kanji: "気持ち", hiragana: "きもち", meaning: "마음, 기분, 감정" },
  { kanji: "壊れる", hiragana: "こわれる", meaning: "고장나다, 부서지다, 파괴되다" },
  { kanji: "一緒", hiragana: "いっしょ", meaning: "같이, 함께" },
  { kanji: "光", hiragana: "ひかり", meaning: "빛" },
  { kanji: "手前", hiragana: "てまえ", meaning: "저, 너" },
  { kanji: "公務員", hiragana: "こうむいん", meaning: "공무원" },
  { kanji: "旅館", hiragana: "りょかん", meaning: "여관" },
  { kanji: "途中", hiragana: "とちゅう", meaning: "도중" },
  { kanji: "サラダ", hiragana: "", meaning: "샐러드" },
  { kanji: "申す", hiragana: "もうす", meaning: "말씀하다" },
  { kanji: "機械", hiragana: "きかい", meaning: "기계" },
  { kanji: "引っ越す", hiragana: "ひっこす", meaning: "이사하다" },
  { kanji: "けれども", hiragana: "", meaning: "~지만, 그러나, 그렇지만" },
  { kanji: "空港", hiragana: "くうこう", meaning: "공항" },
  { kanji: "畳", hiragana: "たたみ", meaning: "다다미" },
  { kanji: "スリッパ", hiragana: "", meaning: "슬리퍼" },
  { kanji: "弁当", hiragana: "べんとう", meaning: "도시락" },
  { kanji: "忘れ物", hiragana: "わすれもの", meaning: "잊어버린 물건, 잃어버린 물건, 분실물" },
  { kanji: "ソフト", hiragana: "", meaning: "소프트, 부드러움, 소프트웨어" },
  { kanji: "辞典", hiragana: "じてん", meaning: "사전" },
  { kanji: "おや", hiragana: "", meaning: "어머나, 이런" },
  { kanji: "有名", hiragana: "ゆうめい", meaning: "유명" },
  { kanji: "ご馳走", hiragana: "ごちそう", meaning: "손님 대접, 진수성찬" },
  { kanji: "下着", hiragana: "したぎ", meaning: "속옷" },
  { kanji: "時代", hiragana: "じだい", meaning: "시대" },
  { kanji: "小学校", hiragana: "しょうがっこう", meaning: "초등학교" },
  { kanji: "個", hiragana: "こ", meaning: "개, ~개" },
  { kanji: "歯", hiragana: "は", meaning: "이, 이빨" },
  { kanji: "説明", hiragana: "せつめい", meaning: "설명" },
  { kanji: "直る", hiragana: "なおる", meaning: "고치다, 바로잡히다, 치료되다, 낫다" },
  { kanji: "島", hiragana: "しま", meaning: "섬" },
  { kanji: "入院", hiragana: "にゅういん", meaning: "입원" },
  { kanji: "入社", hiragana: "にゅうしゃ", meaning: "입사" },
  { kanji: "間違える", hiragana: "まちがえる", meaning: "잘못하다, 틀리다" },
  { kanji: "アフリカ", hiragana: "", meaning: "아프리카" },
  { kanji: "君", hiragana: "きみ", meaning: "자네, 너" },
  { kanji: "食事", hiragana: "しょくじ", meaning: "식사" },
  { kanji: "消しゴム", hiragana: "けしごむ", meaning: "지우개" },
  { kanji: "箱", hiragana: "はこ", meaning: "상자" },
  { kanji: "通り", hiragana: "とおり", meaning: "길, 통함, 종류, 방법" },
  { kanji: "注意", hiragana: "ちゅうい", meaning: "주의" },
  { kanji: "ひと月", hiragana: "ひとつき", meaning: "한 달, 1개월" },
  { kanji: "必要", hiragana: "ひつよう", meaning: "필요" },
  { kanji: "窺う", hiragana: "うかがう", meaning: "엿보다, 살피다, 노리다" },
  { kanji: "貰う", hiragana: "もらう", meaning: "받다" },
  { kanji: "浅い", hiragana: "あさい", meaning: "얕다" },
  { kanji: "駐車場", hiragana: "ちゅうしゃじょう", meaning: "주차장" },
  { kanji: "殆ど", hiragana: "ほとんど", meaning: "대부분, 거의, 대략" },
  { kanji: "飼う", hiragana: "かう", meaning: "기르다, 사육하다" },
  { kanji: "別れる", hiragana: "わかれる", meaning: "헤어지다, 갈라서다, 이별하다" },
  { kanji: "優しい", hiragana: "やさしい", meaning: "상냥하다, 다정하다" },
  { kanji: "紹介", hiragana: "しょうかい", meaning: "소개" },
  { kanji: "入学", hiragana: "にゅうがく", meaning: "입학" },
  { kanji: "寺", hiragana: "てら", meaning: "절, 사찰" },
  { kanji: "字", hiragana: "じ", meaning: "글자, 글씨" },
  { kanji: "下りる", hiragana: "おりる", meaning: "내리다, 내려오다" },
  { kanji: "揺れる", hiragana: "ゆれる", meaning: "흔들리다, 일렁거리다" },
  { kanji: "随分", hiragana: "ずいぶん", meaning: "대단히, 몹시, 상당히, 꽤, 충분히" },
  { kanji: "そう", hiragana: "", meaning: "그렇게, 그리, 그래, 정말" },
  { kanji: "醤油", hiragana: "しょうゆ", meaning: "간장" },
  { kanji: "酷い", hiragana: "ひどい", meaning: "심하다, 가혹하다, 모질다, 너무하다" },
  { kanji: "壊す", hiragana: "こわす", meaning: "파괴하다, 부수다, 고장내다" },
  { kanji: "最初", hiragana: "さいしょ", meaning: "최초" },
  { kanji: "はっきり", hiragana: "", meaning: "확실히, 분명히" },
  { kanji: "ご存じ", hiragana: "ごぞんじ", meaning: "알고 계심" },
  { kanji: "一杯", hiragana: "いっぱい", meaning: "가득" },
  { kanji: "記者", hiragana: "きしゃ", meaning: "기자" },
  { kanji: "中", hiragana: "ちゅう", meaning: "중, 한가운데, 속, 안" },
  { kanji: "固い", hiragana: "かたい", meaning: "단단하다, 딱딱하다" },
  { kanji: "それに", hiragana: "", meaning: "그런데도, 그러함에도, 게다가, 더욱이" },
  { kanji: "焼ける", hiragana: "やける", meaning: "타다, 구워지다" },
  { kanji: "中々", hiragana: "なかなか", meaning: "꽤, 좀처럼, 상당히" },
  { kanji: "疲れる", hiragana: "つかれる", meaning: "지치다, 피로해지다" },
  { kanji: "見物", hiragana: "けんぶつ", meaning: "구경, 볼만한 것, 볼 거리" },
  { kanji: "両方", hiragana: "りょうほう", meaning: "양방, 쌍방" },
  { kanji: "文法", hiragana: "ぶんぽう", meaning: "문법" },
  { kanji: "最近", hiragana: "さいきん", meaning: "최근" },
  { kanji: "梅雨", hiragana: "つゆ", meaning: "장마" },
  { kanji: "手元", hiragana: "てもと", meaning: "수중, 손이 미치는 범위, 자기 주위" },
  { kanji: "事務所", hiragana: "じむしょ", meaning: "사무소" },
  { kanji: "音", hiragana: "おと", meaning: "소리" },
  { kanji: "飾り", hiragana: "かざり", meaning: "꾸밈, 장식, 치장" },
  { kanji: "増える", hiragana: "ふえる", meaning: "늘다, 증가하다" },
  { kanji: "終わり", hiragana: "おわり", meaning: "끝, 마지막" },
  { kanji: "戸", hiragana: "と", meaning: "문" },
  { kanji: "生活", hiragana: "せいかつ", meaning: "생활" },
  { kanji: "此の頃", hiragana: "このごろ", meaning: "요즘, 이즘, 요 며칠" },
  { kanji: "明日", hiragana: "あす", meaning: "명일, 내일" },
  { kanji: "似合う", hiragana: "にあう", meaning: "잘 맞다, 어울리다, 조화되다" },
  { kanji: "ガソリン", hiragana: "", meaning: "가솔린, 휘발유" },
  { kanji: "プレゼント", hiragana: "", meaning: "선물" },
  { kanji: "血", hiragana: "ち", meaning: "피" },
  { kanji: "アクセサリー", hiragana: "", meaning: "액세서리, 장신구" },
  { kanji: "帰り", hiragana: "かえり", meaning: "돌아옴, 돌아감, 귀가" },
  { kanji: "折れる", hiragana: "おれる", meaning: "접히다, 꺾이다, 부러지다" },
  { kanji: "時", hiragana: "とき", meaning: "시간, 시각, 때" },
  { kanji: "天気予報", hiragana: "てんきよほう", meaning: "일기 예보" },
  { kanji: "カレー", hiragana: "", meaning: "카레" },
  { kanji: "出来る", hiragana: "できる", meaning: "할 수 있다, 할 줄 알다, 가능하다" },
  { kanji: "伝える", hiragana: "つたえる", meaning: "전하다, 전도하다, 전달하다" },
  { kanji: "到頭", hiragana: "とうとう", meaning: "드디어, 결국, 마침내" },
  { kanji: "習慣", hiragana: "しゅうかん", meaning: "습관" },
  { kanji: "羽", hiragana: "はね", meaning: "날개" },
  { kanji: "一体", hiragana: "いったい", meaning: "전반적으로, 대체로, 도대체" },
  { kanji: "曇る", hiragana: "くもる", meaning: "흐리다, 흐려지다, 어두워지다" },
  { kanji: "暮れる", hiragana: "くれる", meaning: "저물다, 해가 지다" },
  { kanji: "用意", hiragana: "ようい", meaning: "준비, 대비" },
  { kanji: "花見", hiragana: "はなみ", meaning: "꽃구경, 꽃놀이" },
  { kanji: "柔らかい", hiragana: "やわらかい", meaning: "말랑하다, 부드럽다" },
  { kanji: "地理", hiragana: "ちり", meaning: "지리" },
  { kanji: "技術", hiragana: "ぎじゅつ", meaning: "기술" },
  { kanji: "理由", hiragana: "りゆう", meaning: "이유" },
  { kanji: "経済", hiragana: "けいざい", meaning: "경제" },
  { kanji: "景色", hiragana: "けしき", meaning: "경치" },
  { kanji: "ピアノ", hiragana: "", meaning: "피아노" },
  { kanji: "割れる", hiragana: "われる", meaning: "깨지다, 갈라지다" },
  { kanji: "向こう", hiragana: "むこう", meaning: "저편, 맞은편, 건너편, 저쪽" },
  { kanji: "恥ずかしい", hiragana: "はずかしい", meaning: "부끄럽다, 창피하다" },
  { kanji: "毛", hiragana: "け", meaning: "털" },
  { kanji: "研究室", hiragana: "けんきゅうしつ", meaning: "연구실" },
  { kanji: "ボート", hiragana: "", meaning: "보트" },
  { kanji: "テキスト", hiragana: "", meaning: "텍스트, 교재" },
  { kanji: "校長", hiragana: "こうちょう", meaning: "교장" },
  { kanji: "見付かる", hiragana: "みつかる", meaning: "발견되다, 들키다" },
  { kanji: "森", hiragana: "もり", meaning: "수풀, 삼림, 숲" },
  { kanji: "サンダル", hiragana: "", meaning: "샌들" },
  { kanji: "番", hiragana: "ばん", meaning: "순서, 차례" },
  { kanji: "週間", hiragana: "しゅうかん", meaning: "주간" },
  { kanji: "泊める", hiragana: "とめる", meaning: "숙박시키다, 묵게 하다, 정박시키다" },
  { kanji: "特別", hiragana: "とくべつ", meaning: "특별" },
  { kanji: "踊り", hiragana: "おどり", meaning: "춤, 무용" },
  { kanji: "講堂", hiragana: "こうどう", meaning: "강당" },
  { kanji: "訪ねる", hiragana: "たずねる", meaning: "찾다, 방문하다" },
  { kanji: "深い", hiragana: "ふかい", meaning: "깊다" },
  { kanji: "国産", hiragana: "こくさん", meaning: "국산" },
  { kanji: "骨", hiragana: "ほね", meaning: "뼈, 뼈대" },
  { kanji: "答え", hiragana: "こたえ", meaning: "대답, 해답" },
  { kanji: "歯医者", hiragana: "はいしゃ", meaning: "치과 의사, 치과" },
  { kanji: "渡す", hiragana: "わたす", meaning: "건네주다, 건너게 하다" },
  { kanji: "布団", hiragana: "ふとん", meaning: "이부자리, 이불" },
  { kanji: "語", hiragana: "ご", meaning: "말, 언어, 단어" },
  { kanji: "頼む", hiragana: "たのむ", meaning: "부탁하다" },
  { kanji: "彼女", hiragana: "かのじょ", meaning: "그녀, 여자친구" },
  { kanji: "経験", hiragana: "けいけん", meaning: "경험" },
  { kanji: "トラック", hiragana: "", meaning: "트럭, 화물 자동차" },
  { kanji: "ガス", hiragana: "", meaning: "가스" },
  { kanji: "テニス", hiragana: "", meaning: "테니스" },
  { kanji: "駄目", hiragana: "だめ", meaning: "소용없음, 못씀, 안됨" },
  { kanji: "葡萄", hiragana: "ぶどう", meaning: "포도" },
  { kanji: "回る", hiragana: "まわる", meaning: "돌다, 회전하다" },
  { kanji: "然し", hiragana: "しかし", meaning: "그러나, 그렇지만, 그런데" },
  { kanji: "聞こえる", hiragana: "きこえる", meaning: "들리다" },
  { kanji: "レポート", hiragana: "", meaning: "레포트, 보고서" },
  { kanji: "並ぶ", hiragana: "ならぶ", meaning: "줄지어 늘어서다, 나란히 서다" },
  { kanji: "月", hiragana: "つき", meaning: "달, 달빛, 한 달, 월" },
  { kanji: "社会", hiragana: "しゃかい", meaning: "사회" },
  { kanji: "女性", hiragana: "じょせい", meaning: "여성" },
  { kanji: "濡れる", hiragana: "ぬれる", meaning: "젖다" },
  { kanji: "台", hiragana: "だい", meaning: "대, 받침대" },
  { kanji: "生きる", hiragana: "いきる", meaning: "살다" },
  { kanji: "九つ", hiragana: "ここのつ", meaning: "아홉개, 9개" },
  { kanji: "乗り物", hiragana: "のりもの", meaning: "탈것, 교통편, 교통 기관" },
  { kanji: "代わり", hiragana: "かわり", meaning: "대리, 대용, 대신" },
  { kanji: "側", hiragana: "がわ", meaning: "옆, 곁, 주위, 둘레, 테" },
  { kanji: "スピーチ", hiragana: "", meaning: "스피치, 연설" },
  { kanji: "可笑しい", hiragana: "おかしい", meaning: "우습다, 우스꽝스럽다, 이상하다" },
  { kanji: "進む", hiragana: "すすむ", meaning: "나아가다, 진출하다" },
  { kanji: "大分", hiragana: "だいぶ", meaning: "상당히, 꽤" },
  { kanji: "会場", hiragana: "かいじょう", meaning: "회장" },
  { kanji: "係る", hiragana: "かかる", meaning: "관계되다, 관련되다" },
  { kanji: "自転車", hiragana: "じてんしゃ", meaning: "자전거" },
  { kanji: "乾く", hiragana: "かわく", meaning: "마르다, 건조하다" },
  { kanji: "期間", hiragana: "きかん", meaning: "기간" },
  { kanji: "どんどん", hiragana: "", meaning: "점점, 자꾸, 계속" },
  { kanji: "寄る", hiragana: "よる", meaning: "접근하다, 다가가다, 들르다" },
  { kanji: "毎年", hiragana: "まいとし", meaning: "매년, 매해, 해마다" },
  { kanji: "遠く", hiragana: "とおく", meaning: "먼 곳, 멀리, 훨씬, 매우" },
  { kanji: "通う", hiragana: "かよう", meaning: "다니다, 왕래하다" },
  { kanji: "ダンス", hiragana: "", meaning: "댄스" },
  { kanji: "孫", hiragana: "まご", meaning: "손자, 손주" },
  { kanji: "復習", hiragana: "ふくしゅう", meaning: "복습" },
  { kanji: "プリント", hiragana: "", meaning: "프린트, 인쇄" },
  { kanji: "為", hiragana: "ため", meaning: "위해, 위함" },
  { kanji: "国際", hiragana: "こくさい", meaning: "국제" },
  { kanji: "匂い", hiragana: "におい", meaning: "냄새, 향내" },
  { kanji: "残る", hiragana: "のこる", meaning: "남다, 여분이 생기다" },
  { kanji: "出来る丈", hiragana: "できるだけ", meaning: "가능한 한, 되도록" },
  { kanji: "何", hiragana: "なん", meaning: "무엇" },
  { kanji: "表", hiragana: "おもて", meaning: "표면, 겉" },
  { kanji: "連絡", hiragana: "れんらく", meaning: "연락" },
  { kanji: "全部", hiragana: "ぜんぶ", meaning: "전부" },
  { kanji: "億", hiragana: "おく", meaning: "억" },
  { kanji: "会議", hiragana: "かいぎ", meaning: "회의" },
  { kanji: "形", hiragana: "かたち", meaning: "모양, 형태" },
  { kanji: "絹", hiragana: "きぬ", meaning: "명주, 비단" },
  { kanji: "着く", hiragana: "つく", meaning: "닿다, 도착하다, 붙다, 매달리다" },
  { kanji: "工場", hiragana: "こうじょう", meaning: "공장" },
  { kanji: "列車", hiragana: "れっしゃ", meaning: "열차" },
  { kanji: "転ぶ", hiragana: "ころぶ", meaning: "쓰러지다, 자빠지다, 넘어지다" },
  { kanji: "産業", hiragana: "さんぎょう", meaning: "산업" },
  { kanji: "様", hiragana: "さま", meaning: "님, ~님" },
  { kanji: "興味", hiragana: "きょうみ", meaning: "흥미" },
  { kanji: "あの", hiragana: "", meaning: "저, 저기" },
  { kanji: "育てる", hiragana: "そだてる", meaning: "키우다, 기르다, 양육하다" },
  { kanji: "光る", hiragana: "ひかる", meaning: "빛나다" },
  { kanji: "台風", hiragana: "たいふう", meaning: "태풍" },
  { kanji: "予約", hiragana: "よやく", meaning: "예약" },
  { kanji: "工事", hiragana: "こうじ", meaning: "공사" },
  { kanji: "おばさん", hiragana: "", meaning: "아주머니, 이모, 고모, 숙모" },
  { kanji: "地図", hiragana: "ちず", meaning: "지도" },
  { kanji: "練習", hiragana: "れんしゅう", meaning: "연습" },
  { kanji: "掛ける", hiragana: "かける", meaning: "걸다, 매달다, 잠그다, 채우다" },
  { kanji: "乗り換え", hiragana: "のりかえ", meaning: "갈아탐, 바꿔 탐, 환승" },
  { kanji: "倒れる", hiragana: "たおれる", meaning: "쓰러지다, 넘어지다, 무너지다" },
  { kanji: "自動車", hiragana: "じどうしゃ", meaning: "자동차" },
  { kanji: "運転手", hiragana: "うんてんしゅ", meaning: "운전수" },
  { kanji: "老人", hiragana: "ろうじん", meaning: "노인" },
  { kanji: "動物園", hiragana: "どうぶつえん", meaning: "동물원" },
  { kanji: "皆", hiragana: "みな", meaning: "다, 모두, 전부" },
  { kanji: "大事", hiragana: "だいじ", meaning: "큰일, 중요함, 소중함" },
  { kanji: "世話", hiragana: "せわ", meaning: "폐, 신세" },
  { kanji: "日", hiragana: "ひ", meaning: "해, 햇빛, 볕, 낮, ~날" },
  { kanji: "簡単", hiragana: "かんたん", meaning: "간단" },
  { kanji: "分", hiragana: "ふん", meaning: "분" },
  { kanji: "ジャム", hiragana: "", meaning: "잼" },
  { kanji: "都合", hiragana: "つごう", meaning: "형편, 사정" },
  { kanji: "丁寧", hiragana: "ていねい", meaning: "정중함, 신중함" },
  { kanji: "では", hiragana: "", meaning: "그러면, 그렇다면, 그럼" },
  { kanji: "廊下", hiragana: "ろうか", meaning: "복도" },
  { kanji: "金魚", hiragana: "きんぎょ", meaning: "금붕어" },
  { kanji: "必ず", hiragana: "かならず", meaning: "반드시, 꼭" },
  { kanji: "姉妹", hiragana: "しまい", meaning: "자매" },
  { kanji: "帽子", hiragana: "ぼうし", meaning: "모자" },
  { kanji: "飾る", hiragana: "かざる", meaning: "장식하다, 꾸미다, 치장하다" },
  { kanji: "厳しい", hiragana: "きびしい", meaning: "엄하다, 엄격하다, 심하다" },
  { kanji: "食料品", hiragana: "しょくりょうひん", meaning: "식료품" },
  { kanji: "最後", hiragana: "さいご", meaning: "최후, 마지막" },
  { kanji: "枝", hiragana: "えだ", meaning: "가지, 나뭇가지" },
  { kanji: "怖い", hiragana: "こわい", meaning: "무섭다, 두렵다" },
  { kanji: "稜", hiragana: "そば", meaning: "귀퉁이, 모서리" },
  { kanji: "気に入る", hiragana: "きにいる", meaning: "마음에 들다" },
  { kanji: "竹", hiragana: "たけ", meaning: "대나무" },
  { kanji: "落し物", hiragana: "おとしもの", meaning: "분실물" },
  { kanji: "米", hiragana: "こめ", meaning: "쌀" },
  { kanji: "つまらない", hiragana: "", meaning: "재미없다, 하찮다, 시시하다, 보람이 없다" },
  { kanji: "拾う", hiragana: "ひろう", meaning: "줍다" },
  { kanji: "吹く", hiragana: "ふく", meaning: "불다" },
  { kanji: "法律", hiragana: "ほうりつ", meaning: "법률" },
  { kanji: "曇り", hiragana: "くもり", meaning: "흐림" },
  { kanji: "続ける", hiragana: "つづける", meaning: "계속하다" },
  { kanji: "塵", hiragana: "ごみ", meaning: "쓰레기" },
  { kanji: "ガソリンスタンド", hiragana: "", meaning: "주유소" },
  { kanji: "丁度", hiragana: "ちょうど", meaning: "꼭, 정확히, 마치, 마침, 알맞게" },
  { kanji: "脱ぐ", hiragana: "ぬぐ", meaning: "벗다" },
  { kanji: "林", hiragana: "はやし", meaning: "숲" },
  { kanji: "剃る", hiragana: "そる", meaning: "깎다, 면도하다" },
  { kanji: "手伝う", hiragana: "てつだう", meaning: "돕다" },
  { kanji: "なるほど", hiragana: "", meaning: "정말, 과연" },
  { kanji: "質問", hiragana: "しつもん", meaning: "질문" },
  { kanji: "桜", hiragana: "さくら", meaning: "벚꽃" },
  { kanji: "一生懸命", hiragana: "いっしょうけんめい", meaning: "목숨 걸고 일을 함, 매우 열심히 함" },
  { kanji: "髭", hiragana: "ひげ", meaning: "수염" },
  { kanji: "決める", hiragana: "きめる", meaning: "정하다, 결정하다" },
  { kanji: "セット", hiragana: "", meaning: "세트, 설정" },
  { kanji: "熱い", hiragana: "あつい", meaning: "뜨겁다" },
  { kanji: "貿易", hiragana: "ぼうえき", meaning: "무역" },
  { kanji: "電報", hiragana: "でんぽう", meaning: "전보" },
  { kanji: "負ける", hiragana: "まける", meaning: "지다, 패하다" },
  { kanji: "階", hiragana: "かい", meaning: "층, ~층" },
  { kanji: "豚肉", hiragana: "ぶたにく", meaning: "돼지고기" },
  { kanji: "全然", hiragana: "ぜんぜん", meaning: "전혀, 온통, 모조리" },
  { kanji: "急行", hiragana: "きゅうこう", meaning: "급행" },
  { kanji: "砂", hiragana: "すな", meaning: "모래" },
  { kanji: "大人しい", hiragana: "おとなしい", meaning: "조용하다, 얌전하다, 어른스럽다" },
  { kanji: "いつか", hiragana: "", meaning: "언젠가, 조만간에" },
  { kanji: "直ぐに", hiragana: "すぐに", meaning: "곧, 즉시, 바로" },
  { kanji: "お宅", hiragana: "おたく", meaning: "댁, 당신, 남편" },
  { kanji: "結構", hiragana: "けっこう", meaning: "훌륭함, 좋음, 꽤" },
  { kanji: "市民", hiragana: "しみん", meaning: "시민" },
  { kanji: "踏む", hiragana: "ふむ", meaning: "밟다, 딛다" },
  { kanji: "易しい", hiragana: "やさしい", meaning: "쉽다" },
  { kanji: "雲", hiragana: "くも", meaning: "구름" },
  { kanji: "泊まる", hiragana: "とまる", meaning: "묵다, 숙박하다" },
  { kanji: "利用", hiragana: "りよう", meaning: "이용" },
  { kanji: "発音", hiragana: "はつおん", meaning: "발음" },
  { kanji: "盗む", hiragana: "ぬすむ", meaning: "훔치다" },
  { kanji: "ビール", hiragana: "", meaning: "맥주" },
  { kanji: "運ぶ", hiragana: "はこぶ", meaning: "운반하다, 옮기다" },
  { kanji: "冷蔵庫", hiragana: "れいぞうこ", meaning: "냉장고" },
  { kanji: "マッチ", hiragana: "", meaning: "성냥, 조화, 경기" },
  { kanji: "道具", hiragana: "どうぐ", meaning: "도구" },
  { kanji: "写す", hiragana: "うつす", meaning: "베끼다, 모사하다" },
  { kanji: "社長", hiragana: "しゃちょう", meaning: "사장" },
  { kanji: "バケツ", hiragana: "", meaning: "양동이" },
  { kanji: "足す", hiragana: "たす", meaning: "더하다, 보태다" },
  { kanji: "観光", hiragana: "かんこう", meaning: "관광" },
  { kanji: "家庭", hiragana: "かてい", meaning: "가정" },
  { kanji: "そんなに", hiragana: "", meaning: "그렇게" },
  { kanji: "美術館", hiragana: "びじゅつかん", meaning: "미술관" },
  { kanji: "神社", hiragana: "じんじゃ", meaning: "신사" },
  { kanji: "嘘", hiragana: "うそ", meaning: "거짓, 거짓말" },
  { kanji: "家内", hiragana: "かない", meaning: "아내, 집사람" },
  { kanji: "玩具", hiragana: "おもちゃ", meaning: "장난감, 완구" },
  { kanji: "本当", hiragana: "ほんとう", meaning: "진실, 정말" },
  { kanji: "力", hiragana: "ちから", meaning: "힘" },
  { kanji: "レベル", hiragana: "", meaning: "레벨, 수준, 정도" },
  { kanji: "床屋", hiragana: "とこや", meaning: "이발소" },
  { kanji: "屋上", hiragana: "おくじょう", meaning: "옥상" },
  { kanji: "店員", hiragana: "てんいん", meaning: "점원" },
  { kanji: "先輩", hiragana: "せんぱい", meaning: "선배" },
  { kanji: "妻", hiragana: "つま", meaning: "처, 아내" },
  { kanji: "びっくり", hiragana: "", meaning: "깜짝 놀람" },
  { kanji: "夕べ", hiragana: "ゆうべ", meaning: "저녁때, 해질녁" },
  { kanji: "歌手", hiragana: "かしゅ", meaning: "가수" },
  { kanji: "歴史", hiragana: "れきし", meaning: "역사" },
  { kanji: "文学", hiragana: "ぶんがく", meaning: "문학" },
  { kanji: "ジュース", hiragana: "", meaning: "주스, 쥬스" },
  { kanji: "原因", hiragana: "げんいん", meaning: "원인" },
  { kanji: "関係", hiragana: "かんけい", meaning: "관계" },
  { kanji: "無くなる", hiragana: "なくなる", meaning: "없어지다" },
  { kanji: "方", hiragana: "かた", meaning: "쪽, 편, 방향, 분" },
  { kanji: "会", hiragana: "かい", meaning: "모임, 회" },
  { kanji: "約束", hiragana: "やくそく", meaning: "약속" },
  { kanji: "取り替える", hiragana: "とりかえる", meaning: "갈다, 바꾸다, 교체하다, 교환하다" },
  { kanji: "私", hiragana: "わたくし", meaning: "저, 나" },
  { kanji: "アルコール", hiragana: "", meaning: "알코올" },
  { kanji: "参", hiragana: "さん", meaning: "참가, 참가함" },
  { kanji: "背", hiragana: "せ", meaning: "등, 키" },
  { kanji: "無くす", hiragana: "なくす", meaning: "잃다" },
  { kanji: "盛ん", hiragana: "さかん", meaning: "활발함, 기세 좋음, 맹렬함, 번성함" },
  { kanji: "背広", hiragana: "せびろ", meaning: "신사복" },
  { kanji: "エスカレーター", hiragana: "", meaning: "에스컬레이터" },
  { kanji: "文章", hiragana: "ぶんしょう", meaning: "문장" },
  { kanji: "騒ぐ", hiragana: "さわぐ", meaning: "떠들다, 시끄러워지다" },
  { kanji: "ピクニック", hiragana: "", meaning: "피크닉, 소풍" },
  { kanji: "さっき", hiragana: "", meaning: "아까, 조금 전" },
  { kanji: "営業", hiragana: "えいぎょう", meaning: "영업" },
  { kanji: "肩", hiragana: "かた", meaning: "어깨" },
  { kanji: "招待", hiragana: "しょうたい", meaning: "초대" },
  { kanji: "昨夜", hiragana: "ゆうべ", meaning: "어제 저녁, 어젯밤" },
  { kanji: "外国", hiragana: "がいこく", meaning: "외국" },
  { kanji: "塗る", hiragana: "ぬる", meaning: "바르다, 칠하다, 화장을 하다" },
  { kanji: "回", hiragana: "かい", meaning: "~회, ~번, 횟수" },
  { kanji: "細かい", hiragana: "こまかい", meaning: "세세하다, 상세하다, 미세하다" },
  { kanji: "止む", hiragana: "やむ", meaning: "그치다, 멈추다" },
  { kanji: "度", hiragana: "ど", meaning: "도, 정도" },
  { kanji: "主人", hiragana: "しゅじん", meaning: "주인, 업체의 임자, 일가의 가구주, 남편" },
  { kanji: "数学", hiragana: "すうがく", meaning: "수학" },
  { kanji: "厚い", hiragana: "あつい", meaning: "두껍다, 두텁다, 많다" },
  { kanji: "専門", hiragana: "せんもん", meaning: "전문" },
  { kanji: "欠席", hiragana: "けっせき", meaning: "결석" },
  { kanji: "過ぎる", hiragana: "すぎる", meaning: "지나다, 지나치다, 통과하다" },
  { kanji: "聞き取り", hiragana: "ききとり", meaning: "청취, 듣기, 사정을 들음" },
  { kanji: "住所", hiragana: "じゅうしょ", meaning: "주소" },
  { kanji: "晩", hiragana: "ばん", meaning: "밤, 저녁" },
  { kanji: "筈", hiragana: "はず", meaning: "~할 예정, ~할 리" },
  { kanji: "邪魔", hiragana: "じゃま", meaning: "방해" },
  { kanji: "海岸", hiragana: "かいがん", meaning: "해안" },
  { kanji: "引く", hiragana: "ひく", meaning: "끌다, 잡아끌다, 당기다" },
  { kanji: "鉤", hiragana: "かぎ", meaning: "갈고리" },
  { kanji: "駐車", hiragana: "ちゅうしゃ", meaning: "주차" },
  { kanji: "茶色", hiragana: "ちゃいろ", meaning: "갈색" },
  { kanji: "スーツケース", hiragana: "", meaning: "슈트케이스, 여행용 가방" },
  { kanji: "輸入", hiragana: "ゆにゅう", meaning: "수입" },
  { kanji: "政治", hiragana: "せいじ", meaning: "정치" },
  { kanji: "人口", hiragana: "じんこう", meaning: "인구" },
  { kanji: "展覧会", hiragana: "てんらんかい", meaning: "전람회" },
  { kanji: "通る", hiragana: "とおる", meaning: "통하다, 통과하다, 뚫리다, 지나다, 지나가다" },
  { kanji: "田舎", hiragana: "いなか", meaning: "시골, 지방" },
  { kanji: "算数", hiragana: "さんすう", meaning: "산수" },
  { kanji: "ワイシャツ", hiragana: "", meaning: "와이셔츠" },
  { kanji: "気", hiragana: "き", meaning: "기운, 기, 기력" },
  { kanji: "だから", hiragana: "", meaning: "그러므로, 그러니까, 그래서" },
  { kanji: "申し上げる", hiragana: "もうしあげる", meaning: "말씀드리다, 여쭈다" },
  { kanji: "ちっとも", hiragana: "", meaning: "조금도, 잠시도" },
  { kanji: "集める", hiragana: "あつめる", meaning: "모으다" },
  { kanji: "考える", hiragana: "かんがえる", meaning: "생각하다" },
  { kanji: "十", hiragana: "とお", meaning: "열, 10, 열 살" },
  { kanji: "伺う", hiragana: "うかがう", meaning: "찾다, 듣다, 묻다, 방문하다" },
  { kanji: "嬉しい", hiragana: "うれしい", meaning: "기쁘다" },
  { kanji: "やはり", hiragana: "", meaning: "역시" },
  { kanji: "包む", hiragana: "つつむ", meaning: "싸다, 포장하다" },
  { kanji: "もう", hiragana: "", meaning: "벌써, 이미, 이제, 곧" },
  { kanji: "以上", hiragana: "いじょう", meaning: "이상, ~보다 많음" },
  { kanji: "十分", hiragana: "じゅうぶん", meaning: "충분" },
  { kanji: "直す", hiragana: "なおす", meaning: "고치다, 수리하다, 정정하다, 바로잡다" },
  { kanji: "コンサート", hiragana: "", meaning: "콘서트" },
  { kanji: "彼", hiragana: "かれ", meaning: "그, 그 남자" },
  { kanji: "髪", hiragana: "かみ", meaning: "머리카락" },
  { kanji: "戻る", hiragana: "もどる", meaning: "되돌아오다, 되돌아가다" },
  { kanji: "計画", hiragana: "けいかく", meaning: "계획" },
  { kanji: "連れる", hiragana: "つれる", meaning: "데려오다, 데려가다" },
  { kanji: "封筒", hiragana: "ふうとう", meaning: "봉투" },
  { kanji: "今度", hiragana: "こんど", meaning: "이번, 이 다음, 다음" },
  { kanji: "怒る", hiragana: "おこる", meaning: "성내다, 화내다" },
  { kanji: "戦争", hiragana: "せんそう", meaning: "전쟁" },
  { kanji: "付く", hiragana: "つく", meaning: "붙다, 달라붙다, 매달리다" },
  { kanji: "案内", hiragana: "あんない", meaning: "안내" },
  { kanji: "草", hiragana: "くさ", meaning: "풀, 풀밭" },
  { kanji: "アナウンサー", hiragana: "", meaning: "아나운서" },
  { kanji: "裏", hiragana: "うら", meaning: "뒤, 뒷면, 뒤쪽" },
  { kanji: "足りる", hiragana: "たりる", meaning: "족하다, 충분하다" },
  { kanji: "教育", hiragana: "きょういく", meaning: "교육" },
  { kanji: "講義", hiragana: "こうぎ", meaning: "강의" },
  { kanji: "そろそろ", hiragana: "", meaning: "슬슬" },
  { kanji: "男性", hiragana: "だんせい", meaning: "남성" },
  { kanji: "あれ", hiragana: "", meaning: "저것" },
  { kanji: "一度", hiragana: "いちど", meaning: "한번, 일회, 한차례" },
  { kanji: "遊び", hiragana: "あそび", meaning: "놀이, 놀기" },
  { kanji: "メートル", hiragana: "", meaning: "미터" },
  { kanji: "美味い", hiragana: "うまい", meaning: "맛있다" },
  { kanji: "それで", hiragana: "", meaning: "그래서, 그런 까닭에, 그로 인해서" },
  { kanji: "席", hiragana: "せき", meaning: "자리, 좌석" },
  { kanji: "出掛ける", hiragana: "でかける", meaning: "외출하다, 나가다" },
  { kanji: "夜間", hiragana: "やかん", meaning: "야간" },
  { kanji: "今夜", hiragana: "こんや", meaning: "오늘 밤" },
  { kanji: "国立", hiragana: "こくりつ", meaning: "국립" },
  { kanji: "引き出し", hiragana: "ひきだし", meaning: "서랍, 인출" },
  { kanji: "屋", hiragana: "や", meaning: "가게" },
  { kanji: "大体", hiragana: "だいたい", meaning: "대체, 대개, 대강" },
  { kanji: "太い", hiragana: "ふとい", meaning: "굵다" },
  { kanji: "なるべく", hiragana: "", meaning: "될 수 있는 한, 가능한 한, 되도록" },
  { kanji: "致す", hiragana: "いたす", meaning: "하다, 가져오다, 일으키다" },
  { kanji: "弾く", hiragana: "ひく", meaning: "악기를 연주하다, 치다, 켜다" },
  { kanji: "泣く", hiragana: "なく", meaning: "울다" },
  { kanji: "投げる", hiragana: "なげる", meaning: "던지다" },
  { kanji: "規則", hiragana: "きそく", meaning: "규칙" },
  { kanji: "マスク", hiragana: "", meaning: "마스크" },
  { kanji: "自動", hiragana: "じどう", meaning: "자동" },
  { kanji: "失礼", hiragana: "しつれい", meaning: "실례" },
  { kanji: "親しい", hiragana: "したしい", meaning: "친하다, 사이좋다, 가깝다" },
  { kanji: "支度", hiragana: "したく", meaning: "준비, 채비" },
  { kanji: "選ぶ", hiragana: "えらぶ", meaning: "고르다, 선택하다, 택하다" },
  { kanji: "ボール", hiragana: "", meaning: "볼, 공" },
  { kanji: "郊外", hiragana: "こうがい", meaning: "교외" },
  { kanji: "そうして", hiragana: "", meaning: "그리고, 그러고 나서, 그리하여" },
  { kanji: "中止", hiragana: "ちゅうし", meaning: "중지" },
  { kanji: "内部", hiragana: "ないぶ", meaning: "내부" },
  { kanji: "水道", hiragana: "すいどう", meaning: "수도, 상수도" },
  { kanji: "返事", hiragana: "へんじ", meaning: "대답, 답장" },
  { kanji: "留守", hiragana: "るす", meaning: "부재중" },
  { kanji: "空気", hiragana: "くうき", meaning: "공기, 분위기" },
  { kanji: "洗濯", hiragana: "せんたく", meaning: "세탁, 빨래" },
  { kanji: "並べる", hiragana: "ならべる", meaning: "늘어놓다, 나란히 하다, 견주다" },
  { kanji: "滑る", hiragana: "すべる", meaning: "미끄러지다" },
  { kanji: "頂く", hiragana: "いただく", meaning: "받다" },
  { kanji: "港", hiragana: "みなと", meaning: "항구" },
  { kanji: "アジア", hiragana: "", meaning: "아시아" },
  { kanji: "押入れ", hiragana: "おしいれ", meaning: "벽장" },
  { kanji: "ずっと", hiragana: "", meaning: "훨씬, 쭉, 계속" },
  { kanji: "思い出す", hiragana: "おもいだす", meaning: "생각해 내다, 생각나다, 떠올리다" },
  { kanji: "比べる", hiragana: "くらべる", meaning: "비교하다, 대조하다, 경쟁하다" },
  { kanji: "ドレス", hiragana: "", meaning: "드레스" },
  { kanji: "勤める", hiragana: "つとめる", meaning: "종사하다, 근무하다" },
  { kanji: "値段", hiragana: "ねだん", meaning: "값, 가격" },
  { kanji: "仰る", hiragana: "おっしゃる", meaning: "말씀하시다" },
  { kanji: "半分", hiragana: "はんぶん", meaning: "반, 절반" },
  { kanji: "触る", hiragana: "さわる", meaning: "닿다, 손을 대다, 만지다" },
  { kanji: "手袋", hiragana: "てぶくろ", meaning: "장갑" },
  { kanji: "ページ", hiragana: "", meaning: "페이지" },
  { kanji: "叱る", hiragana: "しかる", meaning: "꾸짖다, 야단치다, 혼내다" },
  { kanji: "続く", hiragana: "つづく", meaning: "계속되다, 지속되다, 연달다, 잇따르다, 이어지다" },
  { kanji: "欲しい", hiragana: "ほしい", meaning: "가지고 싶다, 원하다, 바라다" },
  { kanji: "今回", hiragana: "こんかい", meaning: "이번 회, 이번" },
  { kanji: "安心", hiragana: "あんしん", meaning: "안심" },
  { kanji: "昼間", hiragana: "ひるま", meaning: "주간, 낮" },
  { kanji: "都", hiragana: "と", meaning: "도시, 도" },
  { kanji: "交通", hiragana: "こうつう", meaning: "교통" },
  { kanji: "無理", hiragana: "むり", meaning: "무리, 할 수 없음" },
  { kanji: "爪", hiragana: "つめ", meaning: "손톱, 발톱" },
  { kanji: "違う", hiragana: "ちがう", meaning: "다르다, 틀리다, 잘못되다" },
  { kanji: "オートバイ", hiragana: "", meaning: "오토바이" },
  { kanji: "亡くなる", hiragana: "なくなる", meaning: "죽다, 돌아가시다" },
  { kanji: "事", hiragana: "こと", meaning: "일, 것, 경우, 사항" },
  { kanji: "等", hiragana: "など", meaning: "따위, 등" },
  { kanji: "痩せる", hiragana: "やせる", meaning: "여위다, 살이 빠지다" },
  { kanji: "葉", hiragana: "は", meaning: "잎, 잎사귀" },
  { kanji: "只今", hiragana: "ただいま", meaning: "지금, 현재, 방금, 이제 막" },
  { kanji: "植える", hiragana: "うえる", meaning: "심다" },
  { kanji: "小鳥", hiragana: "ことり", meaning: "작은 새" },
  { kanji: "片付ける", hiragana: "かたづける", meaning: "치우다, 정돈하다, 정리하다" },
  { kanji: "卒業", hiragana: "そつぎょう", meaning: "졸업" },
  { kanji: "サイン", hiragana: "", meaning: "사인, 서명, 신호" },
  { kanji: "眠い", hiragana: "ねむい", meaning: "졸리다" },
  { kanji: "世界", hiragana: "せかい", meaning: "세계" },
  { kanji: "自由", hiragana: "じゆう", meaning: "자유" },
  { kanji: "砂糖", hiragana: "さとう", meaning: "설탕" },
  { kanji: "それから", hiragana: "", meaning: "그 다음에, 그리고, 그 뒤, 그 이래" },
  { kanji: "珍しい", hiragana: "めずらしい", meaning: "드물다, 희귀하다" },
  { kanji: "下げる", hiragana: "さげる", meaning: "내리다, 내려주다" },
  { kanji: "夢", hiragana: "ゆめ", meaning: "꿈" },
  { kanji: "大抵", hiragana: "たいてい", meaning: "대개, 대부분, 대체, 대충, 대강" },
  { kanji: "寝坊", hiragana: "ねぼう", meaning: "늦잠, 잠꾸러기" },
  { kanji: "指輪", hiragana: "ゆびわ", meaning: "반지" },
  { kanji: "お陰", hiragana: "おかげ", meaning: "덕, 덕택, 덕분" },
  { kanji: "下宿", hiragana: "げしゅく", meaning: "하숙, 하숙집" },
  { kanji: "閉じる", hiragana: "とじる", meaning: "닫히다, 끝나다, 닫다" },
  { kanji: "差す", hiragana: "さす", meaning: "쓰다, 꽂다" },
  { kanji: "似る", hiragana: "にる", meaning: "닮다, 비슷하다" },
  { kanji: "すると", hiragana: "", meaning: "그러자, 그랬더니, 그러면, 그렇다면" },
  { kanji: "仕舞う", hiragana: "しまう", meaning: "끝나다, 끝내다, 마치다" },
  { kanji: "酔い", hiragana: "よい", meaning: "취함, 취기, 멀미" },
  { kanji: "止める", hiragana: "とめる", meaning: "멈추다, 세우다, 정지하다, 말리다" },
  { kanji: "腕", hiragana: "うで", meaning: "팔" },
  { kanji: "熱", hiragana: "ねつ", meaning: "열" },
  { kanji: "客", hiragana: "きゃく", meaning: "손님, 여객" },
  { kanji: "試験", hiragana: "しけん", meaning: "시험" },
  { kanji: "首", hiragana: "くび", meaning: "목" },
  { kanji: "迎える", hiragana: "むかえる", meaning: "맞이하다, 맞다, 마중하다" },
  { kanji: "ステレオ", hiragana: "", meaning: "스테레오, 입체, 입체 장치" },
  { kanji: "工業", hiragana: "こうぎょう", meaning: "공업" },
  { kanji: "それほど", hiragana: "", meaning: "그렇게, 그다지, 그만큼" },
  { kanji: "建つ", hiragana: "たつ", meaning: "서다, 세워지다" },
  { kanji: "レコード", hiragana: "", meaning: "레코드, 음반, 축음기판" },
  { kanji: "地震", hiragana: "じしん", meaning: "지진" },
  { kanji: "壁", hiragana: "かべ", meaning: "벽" },
  { kanji: "僕", hiragana: "ぼく", meaning: "저, 나" },
  { kanji: "寂しい", hiragana: "さびしい", meaning: "외롭다, 쓸쓸하다" },
  { kanji: "飛行場", hiragana: "ひこうじょう", meaning: "비행장" },
  { kanji: "事故", hiragana: "じこ", meaning: "사고" },
  { kanji: "売り場", hiragana: "うりば", meaning: "매장, 파는 곳, 판매장, 매표소" },
  { kanji: "楽しみ", hiragana: "たのしみ", meaning: "즐거움, 낙, 기대" },
  { kanji: "知る", hiragana: "しる", meaning: "알다" },
  { kanji: "そして", hiragana: "", meaning: "그리고" },
  { kanji: "すっかり", hiragana: "", meaning: "죄다, 모두, 완전히, 몽땅" },
  { kanji: "本棚", hiragana: "ほんだな", meaning: "책꽂이, 책장" },
  { kanji: "頑張る", hiragana: "がんばる", meaning: "열심히 하다, 힘내다" },
  { kanji: "遠慮", hiragana: "えんりょ", meaning: "염려, 사양" },
  { kanji: "命", hiragana: "いのち", meaning: "목숨, 생명" },
  { kanji: "積もり", hiragana: "つもり", meaning: "쌓임, 어림, 견적" },
  { kanji: "涼しい", hiragana: "すずしい", meaning: "시원하다, 선선하다, 서늘하다" },
  { kanji: "大使館", hiragana: "たいしかん", meaning: "대사관" },
  { kanji: "多分", hiragana: "たぶん", meaning: "아마" },
  { kanji: "村", hiragana: "むら", meaning: "마을, 촌락" },
  { kanji: "昼休み", hiragana: "ひるやすみ", meaning: "점심 시간" },
  { kanji: "変", hiragana: "へん", meaning: "변화, 이상함" },
  { kanji: "タイプ", hiragana: "", meaning: "타입" },
  { kanji: "警察", hiragana: "けいさつ", meaning: "경찰" },
  { kanji: "パーティー", hiragana: "", meaning: "파티" },
  { kanji: "悲しい", hiragana: "かなしい", meaning: "슬프다, 애처롭다" },
  { kanji: "行く", hiragana: "いく", meaning: "가다" },
  { kanji: "文書", hiragana: "ぶんしょ", meaning: "문서" },
  { kanji: "旅行", hiragana: "りょこう", meaning: "여행" },
  { kanji: "父親", hiragana: "ちちおや", meaning: "부친" },
  { kanji: "以内", hiragana: "いない", meaning: "~이내, 이내" },
  { kanji: "ヶ月", hiragana: "かげつ", meaning: "~개월, 개월" },
  { kanji: "石", hiragana: "いし", meaning: "돌, 바위" },
  { kanji: "広さ", hiragana: "ひろさ", meaning: "넓이" },
  { kanji: "危険", hiragana: "きけん", meaning: "위험" },
  { kanji: "以外", hiragana: "いがい", meaning: "이외" },
  { kanji: "若い", hiragana: "わかい", meaning: "젊다, 어리다" },
  { kanji: "昔", hiragana: "むかし", meaning: "옛날, 예전" },
  { kanji: "間", hiragana: "あいだ", meaning: "사이, 간격, 틈, ~동안" },
  { kanji: "初めて", hiragana: "はじめて", meaning: "처음, 비로소, 첫 번째" },
  { kanji: "おじ", hiragana: "", meaning: "삼촌" },
  { kanji: "冷える", hiragana: "ひえる", meaning: "차가워지다, 식다, 냉담해지다" },
  { kanji: "下がる", hiragana: "さがる", meaning: "내려가다, 떨어지다" },
  { kanji: "星", hiragana: "ほし", meaning: "별" },
  { kanji: "水泳", hiragana: "すいえい", meaning: "수영" },
  { kanji: "準備", hiragana: "じゅんび", meaning: "준비" },
  { kanji: "冷房", hiragana: "れいぼう", meaning: "냉방" },
  { kanji: "番組", hiragana: "ばんぐみ", meaning: "방송, 프로그램" },
  { kanji: "鳴る", hiragana: "なる", meaning: "울리다, 소리가 나다, 떨치다" },
  { kanji: "別", hiragana: "べつ", meaning: "구별, 차이, 다름" },
  { kanji: "近所", hiragana: "きんじょ", meaning: "근처" },
  { kanji: "茶碗", hiragana: "ちゃわん", meaning: "찻종, 밥공기" },
  { kanji: "故障", hiragana: "こしょう", meaning: "고장" },
  { kanji: "コンピューター", hiragana: "", meaning: "컴퓨터" },
  { kanji: "八つ", hiragana: "やっつ", meaning: "여덟개, 8개" },
  { kanji: "泥棒", hiragana: "どろぼう", meaning: "도둑질, 도둑" },
  { kanji: "差し上げる", hiragana: "さしあげる", meaning: "들어 올리다, ~해 드리다" },
  { kanji: "知らせる", hiragana: "しらせる", meaning: "알리다, 통지하다, 통보하다" },
  { kanji: "宜しい", hiragana: "よろしい", meaning: "좋다" },
  { kanji: "本気", hiragana: "ほんき", meaning: "진심" },
  { kanji: "捕まえる", hiragana: "つかまえる", meaning: "붙잡다, 붙들다" },
  { kanji: "格好", hiragana: "かっこう", meaning: "모습, 꼴" },
  { kanji: "張る", hiragana: "はる", meaning: "뻗다, 뻗어나다" },
  { kanji: "下手", hiragana: "へた", meaning: "서투름, 어중간함, 어설픔" },
  { kanji: "細い", hiragana: "ほそい", meaning: "가늘다, 좁다" },
  { kanji: "願う", hiragana: "ねがう", meaning: "원하다, 바라다" },
  { kanji: "苦い", hiragana: "にがい", meaning: "쓰다, 씁쓸하다" },
  { kanji: "年", hiragana: "ねん", meaning: "년, 해, 한 해" },
  { kanji: "字引", hiragana: "じびき", meaning: "옥편, 사전" },
  { kanji: "落とす", hiragana: "おとす", meaning: "떨어뜨리다, 놓치다" },
  { kanji: "縦", hiragana: "たて", meaning: "세로" },
  { kanji: "特急", hiragana: "とっきゅう", meaning: "특급" },
  { kanji: "放送", hiragana: "ほうそう", meaning: "방송" },
  { kanji: "生産", hiragana: "せいさん", meaning: "생산" },
  { kanji: "辞める", hiragana: "やめる", meaning: "그만두다, 중지하다, 사직하다" },
  { kanji: "飴", hiragana: "あめ", meaning: "사탕, 엿" },
  { kanji: "舌", hiragana: "した", meaning: "혀" },
  { kanji: "出来る", hiragana: "できる", meaning: "생기다, 가능하다, 할 수 있다" },
  { kanji: "出発", hiragana: "しゅっぱつ", meaning: "출발" },
  { kanji: "サンドイッチ", hiragana: "", meaning: "샌드위치" },
  { kanji: "将来", hiragana: "しょうらい", meaning: "장래" },
  { kanji: "虫", hiragana: "むし", meaning: "벌레" },
  { kanji: "趣味", hiragana: "しゅみ", meaning: "취미" },
  { kanji: "出席", hiragana: "しゅっせき", meaning: "출석" },
  { kanji: "人形", hiragana: "にんぎょう", meaning: "인형" },
  { kanji: "船", hiragana: "ふね", meaning: "배" },
  { kanji: "動く", hiragana: "うごく", meaning: "움직이다, 작동하다" },
  { kanji: "グラム", hiragana: "", meaning: "그램" },
  { kanji: "特に", hiragana: "とくに", meaning: "특히, 특별히" },
  { kanji: "空く", hiragana: "すく", meaning: "비다, 비어 있다, 열리다, 한가하다" },
  { kanji: "積もる", hiragana: "つもる", meaning: "쌓이다" },
  { kanji: "郵便局", hiragana: "ゆうびんきょく", meaning: "우체국" },
  { kanji: "立派", hiragana: "りっぱ", meaning: "훌륭함" },
  { kanji: "ガラス", hiragana: "", meaning: "유리" },
  { kanji: "祈る", hiragana: "いのる", meaning: "빌다, 기도하다, 기원하다" },
  { kanji: "決まる", hiragana: "きまる", meaning: "정해지다, 결정되다" },
  { kanji: "橋", hiragana: "はし", meaning: "다리, 교랑" },
  { kanji: "大切", hiragana: "たいせつ", meaning: "중요, 귀중, 소중" },
  { kanji: "言葉", hiragana: "ことば", meaning: "말, 언어" },
  { kanji: "ゲーム", hiragana: "", meaning: "게임" },
  { kanji: "捨てる", hiragana: "すてる", meaning: "버리다" },
  { kanji: "電灯", hiragana: "でんとう", meaning: "전등" },
  { kanji: "込む", hiragana: "こむ", meaning: "혼잡하다, 붐비다" },
  { kanji: "金持ち", hiragana: "かねもち", meaning: "부자" },
  { kanji: "スーツ", hiragana: "", meaning: "수트, 양복" },
  { kanji: "きっと", hiragana: "", meaning: "분명, 꼭, 반드시" },
  { kanji: "始まり", hiragana: "はじまり", meaning: "시작, 시초, 기원" },
  { kanji: "戻す", hiragana: "もどす", meaning: "되돌리다" },
  { kanji: "予定", hiragana: "よてい", meaning: "예정" },
  { kanji: "普通", hiragana: "ふつう", meaning: "보통, 대개" },
  { kanji: "合う", hiragana: "あう", meaning: "합쳐지다, 서로 ~하다, 맞다" },
  { kanji: "真面目", hiragana: "まじめ", meaning: "착실함, 성실함, 진지함" },
  { kanji: "文化", hiragana: "ぶんか", meaning: "문화" },
  { kanji: "心", hiragana: "こころ", meaning: "마음" },
  { kanji: "場所", hiragana: "ばしょ", meaning: "장소, 위치" },
  { kanji: "窓口", hiragana: "まどぐち", meaning: "창구" },
  { kanji: "ポスト", hiragana: "", meaning: "우체통, 우편함" },
  { kanji: "焼く", hiragana: "やく", meaning: "굽다, 태우다, 애태우다" },
  { kanji: "晴れ", hiragana: "はれ", meaning: "하늘이 갬, 날씨가 좋음" },
  { kanji: "下さる", hiragana: "くださる", meaning: "주시다" },
  { kanji: "喧嘩", hiragana: "けんか", meaning: "다툼, 싸움" },
  { kanji: "太る", hiragana: "ふとる", meaning: "살찌다" },
  { kanji: "柔道", hiragana: "じゅうどう", meaning: "유도" },
  { kanji: "着る", hiragana: "きる", meaning: "입다" },
  { kanji: "片仮名", hiragana: "かたかな", meaning: "가타카나, 카타카나" },
  { kanji: "試合", hiragana: "しあい", meaning: "시합" },
  { kanji: "日記", hiragana: "にっき", meaning: "일기" },
  { kanji: "反対", hiragana: "はんたい", meaning: "반대" },
  { kanji: "運転", hiragana: "うんてん", meaning: "운전" },
  { kanji: "くれる", hiragana: "", meaning: "주다" },
  { kanji: "他界", hiragana: "たかい", meaning: "타계, 죽음, 인간계 이외의 세계" },
  { kanji: "これから", hiragana: "", meaning: "지금부터, 이제부터, 앞으로" },
  { kanji: "祖父", hiragana: "そふ", meaning: "조부, 할아버지" },
  { kanji: "取る", hiragana: "とる", meaning: "잡다, 들다, 쥐다" },
  { kanji: "止まる", hiragana: "とまる", meaning: "멈추다, 멎다, 그치다, 정지하다, 서다" },
  { kanji: "賛成", hiragana: "さんせい", meaning: "찬성" },
  { kanji: "全体", hiragana: "ぜんたい", meaning: "전체" },
  { kanji: "一々", hiragana: "いちいち", meaning: "일일이, 하나하나" },
  { kanji: "アメリカ", hiragana: "", meaning: "아메리카, 미국" },
  { kanji: "それでは", hiragana: "", meaning: "그러면, 그럼, 그렇다면" },
  { kanji: "正月", hiragana: "しょうがつ", meaning: "정월, 설" },
  { kanji: "指", hiragana: "ゆび", meaning: "손가락" },
  { kanji: "子", hiragana: "こ", meaning: "자식, 아이" },
  { kanji: "若し", hiragana: "もし", meaning: "만약, 만일, 혹시" },
  { kanji: "お祭り", hiragana: "おまつり", meaning: "축제" },
  { kanji: "掃除", hiragana: "そうじ", meaning: "청소" },
  { kanji: "建てる", hiragana: "たてる", meaning: "세우다, 짓다" },
  { kanji: "中学校", hiragana: "ちゅうがっこう", meaning: "중학교" },
  { kanji: "万年筆", hiragana: "まんねんひつ", meaning: "만년필" },
  { kanji: "かなり", hiragana: "", meaning: "제법, 상당히, 꽤" },
  { kanji: "以下", hiragana: "いか", meaning: "이하" },
  { kanji: "小説", hiragana: "しょうせつ", meaning: "소설" },
  { kanji: "係る", hiragana: "かかる", meaning: "관계되다, 관여하다, 연루되다" },
  { kanji: "味", hiragana: "あじ", meaning: "맛" },
  { kanji: "毎月", hiragana: "まいつき", meaning: "매달, 매월, 달마다" },
  { kanji: "品物", hiragana: "しなもの", meaning: "물품, 물건" },
  { kanji: "季節", hiragana: "きせつ", meaning: "계절" },
  { kanji: "眠たい", hiragana: "ねむたい", meaning: "졸리다" },
  { kanji: "両親", hiragana: "りょうしん", meaning: "양친, 부모" },
  { kanji: "バター", hiragana: "", meaning: "버터" },
  { kanji: "祖母", hiragana: "そぼ", meaning: "조모, 할머니" },
  { kanji: "思う", hiragana: "おもう", meaning: "생각하다" },
  { kanji: "スーパー", hiragana: "", meaning: "슈퍼" },
  { kanji: "素晴らしい", hiragana: "すばらしい", meaning: "훌륭하다, 근사하다, 굉장하다" },
  { kanji: "如何", hiragana: "いかが", meaning: "어떻게, 어떻습니까" },
  { kanji: "じゃ", hiragana: "", meaning: "그럼" },
  { kanji: "自分", hiragana: "じぶん", meaning: "자기, 자신" },
  { kanji: "夫", hiragana: "おっと", meaning: "남편" },
  { kanji: "開く", hiragana: "ひらく", meaning: "열리다, 열다" },
  { kanji: "娘", hiragana: "むすめ", meaning: "딸" },
  { kanji: "糸", hiragana: "いと", meaning: "실" },
  { kanji: "ピンク", hiragana: "", meaning: "핑크" },
  { kanji: "笑う", hiragana: "わらう", meaning: "웃다" },
  { kanji: "会話", hiragana: "かいわ", meaning: "회화" },
  { kanji: "受ける", hiragana: "うける", meaning: "받다" },
  { kanji: "ベッド", hiragana: "", meaning: "침대" },
  { kanji: "年代", hiragana: "ねんだい", meaning: "연대, 경과한 시대" },
  { kanji: "起こす", hiragana: "おこす", meaning: "일으키다" },
  { kanji: "いらっしゃる", hiragana: "", meaning: "계시다, 오시다" },
  { kanji: "遣る", hiragana: "やる", meaning: "보내다, 다니게 하다, 하다, 주다" },
  { kanji: "教会", hiragana: "きょうかい", meaning: "교회" },
  { kanji: "為さる", hiragana: "なさる", meaning: "하시다" },
  { kanji: "着物", hiragana: "きもの", meaning: "기모노" },
  { kanji: "割る", hiragana: "わる", meaning: "나누다, 깨다" },
  { kanji: "始める", hiragana: "はじめる", meaning: "시작하다" },
  { kanji: "仕方", hiragana: "しかた", meaning: "방법, 수단" },
  { kanji: "杯", hiragana: "はい", meaning: "잔, 술잔" },
  { kanji: "冷たい", hiragana: "つめたい", meaning: "차갑다, 냉정하다, 쌀쌀하다" },
  { kanji: "決して", hiragana: "けっして", meaning: "결코, 절대로" },
  { kanji: "態々", hiragana: "わざわざ", meaning: "일부러, 고의로" },
  { kanji: "勿論", hiragana: "もちろん", meaning: "물론, 당연히" },
  { kanji: "彼ら", hiragana: "かれら", meaning: "그들, 그 사람들" },
  { kanji: "市", hiragana: "し", meaning: "시" },
  { kanji: "働く", hiragana: "はたらく", meaning: "일하다, 일을 하다, 활동하다" },
  { kanji: "棚", hiragana: "たな", meaning: "선반" },
  { kanji: "火事", hiragana: "かじ", meaning: "화재" },
  { kanji: "点", hiragana: "てん", meaning: "점, 점수" },
  { kanji: "用事", hiragana: "ようじ", meaning: "볼일, 용무, 용건" },
  { kanji: "懸ける", hiragana: "かける", meaning: "걸다, 늘어뜨리다, 달다" },
  { kanji: "久しぶり", hiragana: "ひさしぶり", meaning: "오래간만, 오랜만" },
  { kanji: "フォーク", hiragana: "", meaning: "포크" },
  { kanji: "輸出", hiragana: "ゆしゅつ", meaning: "수출" },
  { kanji: "就ける", hiragana: "つける", meaning: "지위에 앉히다, 자리에 오르게 하다" },
  { kanji: "失敗", hiragana: "しっぱい", meaning: "실패" },
  { kanji: "相談", hiragana: "そうだん", meaning: "상담" },
  { kanji: "走る", hiragana: "はしる", meaning: "달리다" },
  { kanji: "坂", hiragana: "さか", meaning: "비탈길, 고개, 언덕" },
  { kanji: "支払い", hiragana: "しはらい", meaning: "지불, 지급" },
  { kanji: "怪我", hiragana: "けが", meaning: "상처, 부상" },
  { kanji: "湯", hiragana: "ゆ", meaning: "뜨거운 물, 데운 물" },
  { kanji: "本当に", hiragana: "ほんとうに", meaning: "정말로, 실로, 참으로" },
];