// lib/words_54_58.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_54_58: Word[] = [
  { kanji: "若し", hiragana: "もし", meaning: "만약, 만일, 혹시" },
  { kanji: "お祭り", hiragana: "おまつり", meaning: "축제" },
  { kanji: "掃除", hiragana: "そうじ", meaning: "청소" },
  { kanji: "建てる", hiragana: "たてる", meaning: "세우다, 짓다" },
  { kanji: "中学校", hiragana: "ちゅうがっこう", meaning: "중학교" },
  { kanji: "万年筆", hiragana: "まんねんひつ", meaning: "만년필" },
  { kanji: "かなり", hiragana: "", meaning: "제법, 상당히, 꽤" },
  { kanji: "以下", hiragana: "いか", meaning: "이하" },
  { kanji: "小説", hiragana: "しょうせつ", meaning: "소설" },
  { kanji: "係る", hiragana: "かかる", meaning: "관계되다, 관여하다, 연루되다" },
  { kanji: "味", hiragana: "あじ", meaning: "맛" },
  { kanji: "毎月", hiragana: "まいつき", meaning: "매달, 매월, 달마다" },
  { kanji: "品物", hiragana: "しなもの", meaning: "물품, 물건" },
  { kanji: "季節", hiragana: "きせつ", meaning: "계절" },
  { kanji: "眠たい", hiragana: "ねむたい", meaning: "졸리다" },
  { kanji: "両親", hiragana: "りょうしん", meaning: "양친, 부모" },
  { kanji: "バター", hiragana: "", meaning: "버터" },
  { kanji: "祖母", hiragana: "そぼ", meaning: "조모, 할머니" },
  { kanji: "思う", hiragana: "おもう", meaning: "생각하다" },
  { kanji: "スーパー", hiragana: "", meaning: "슈퍼" },
  { kanji: "素晴らしい", hiragana: "すばらしい", meaning: "훌륭하다, 근사하다, 굉장하다" },
  { kanji: "如何", hiragana: "いかが", meaning: "어떻게, 어떻습니까" },
  { kanji: "しゃ", hiragana: "", meaning: "그럼" },
  { kanji: "自分", hiragana: "じぶん", meaning: "자기, 자신" },
  { kanji: "夫", hiragana: "おっと", meaning: "남편" },
  { kanji: "開く", hiragana: "ひらく", meaning: "열리다, 열다" },
  { kanji: "娘", hiragana: "むすめ", meaning: "딸" },
  { kanji: "糸", hiragana: "いと", meaning: "실" },
  { kanji: "ピック", hiragana: "", meaning: "핑크" },
  { kanji: "笑う", hiragana: "わらう", meaning: "웃다" },
  { kanji: "会話", hiragana: "かいわ", meaning: "회화" },
  { kanji: "受ける", hiragana: "うける", meaning: "받다" },
  { kanji: "ベッド", hiragana: "", meaning: "침대" },
  { kanji: "年代", hiragana: "ねんだい", meaning: "연대, 경과한 시대" },
  { kanji: "起こす", hiragana: "おこす", meaning: "일으키다" },
  { kanji: "いらっしゃる", hiragana: "", meaning: "계시다, 오시다" },
  { kanji: "遣る", hiragana: "やる", meaning: "보내다, 다니게 하다, 하다, 주다" },
  { kanji: "教会", hiragana: "きょうかい", meaning: "교회" },
  { kanji: "為さる", hiragana: "なさる", meaning: "하시다" },
  { kanji: "着物", hiragana: "きもの", meaning: "기모노" },
  { kanji: "割る", hiragana: "わる", meaning: "나누다, 깨다" },
  { kanji: "始める", hiragana: "はじめる", meaning: "시작하다" },
  { kanji: "仕方", hiragana: "しかた", meaning: "방법, 수단" },
  { kanji: "杯", hiragana: "はい", meaning: "잔, 술잔" },
  { kanji: "冷たい", hiragana: "つめたい", meaning: "차갑다, 냉정하다, 쌀쌀하다" },
  { kanji: "決して", hiragana: "けっして", meaning: "결고, 절대로" },
  { kanji: "態々", hiragana: "わざわざ", meaning: "일부러, 고의로" },
  { kanji: "勿論", hiragana: "もちろん", meaning: "물론, 당연히" },
  { kanji: "彼ら", hiragana: "かれら", meaning: "그들, 그 사람들" },
  { kanji: "市", hiragana: "し", meaning: "시" },
  { kanji: "働く", hiragana: "はたらく", meaning: "일하다, 일을 하다, 활동하다" },
  { kanji: "棚", hiragana: "たな", meaning: "선반" },
  { kanji: "火事", hiragana: "かじ", meaning: "화재" },
  { kanji: "点", hiragana: "てん", meaning: "점, 점수" },
  { kanji: "用事", hiragana: "ようじ", meaning: "볼일, 용무, 용건" },
  { kanji: "懸ける", hiragana: "かける", meaning: "걸다, 늘어뜨리다, 달다" },
  { kanji: "久しぶり", hiragana: "ひさしぶり", meaning: "오래간만" },
  { kanji: "フォーク", hiragana: "", meaning: "포크" },
  { kanji: "輸出", hiragana: "ゆしゅつ", meaning: "수출" },
  { kanji: "就ける", hiragana: "つける", meaning: "지위에 앉히다, 자리에 오르게 하다" },
  { kanji: "失敗", hiragana: "しっぱい", meaning: "실패" },
  { kanji: "相談", hiragana: "そうだん", meaning: "상담" },
  { kanji: "走る", hiragana: "はしる", meaning: "달리다" },
  { kanji: "坂", hiragana: "さか", meaning: "비탈길, 고개, 언덕" },
  { kanji: "支払い", hiragana: "しはらい", meaning: "지불, 지급" },
  { kanji: "怪我", hiragana: "けが", meaning: "상처, 부상" },
  { kanji: "湯", hiragana: "ゆ", meaning: "뜨거운 물, 데운 물" },
  { kanji: "本当に", hiragana: "ほんとうに", meaning: "정말로, 실로, 참으로" },
];