// lib/words_49_53.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_49_53: Word[] = [
  { kanji: "字引", hiragana: "じびき", meaning: "옥편, 사전" },
  { kanji: "落とす", hiragana: "おとす", meaning: "떨어뜨리다, 놓치다" },
  { kanji: "縦", hiragana: "たて", meaning: "세로" },
  { kanji: "特急", hiragana: "とっきゅう", meaning: "특급" },
  { kanji: "放送", hiragana: "ほうそう", meaning: "방송" },
  { kanji: "生産", hiragana: "せいさん", meaning: "생산" },
  { kanji: "辞める", hiragana: "やめる", meaning: "그만두다, 중지하다, 사직하다" },
  { kanji: "飴", hiragana: "あめ", meaning: "사탕, 엿" },
  { kanji: "舌", hiragana: "した", meaning: "혀" },
  { kanji: "出来る", hiragana: "できる", meaning: "생기다, 가능하다, 할 수 있다" },
  { kanji: "出発", hiragana: "しゅっぱつ", meaning: "출발" },
  { kanji: "サンドイッチ", hiragana: "", meaning: "샌드위치" },
  { kanji: "将来", hiragana: "しょうらい", meaning: "장래" },
  { kanji: "虫", hiragana: "むし", meaning: "벌레" },
  { kanji: "趣味", hiragana: "しゅみ", meaning: "취미" },
  { kanji: "出席", hiragana: "しゅっせき", meaning: "출석" },
  { kanji: "人形", hiragana: "にんぎょう", meaning: "인형" },
  { kanji: "船", hiragana: "ふね", meaning: "배" },
  { kanji: "動く", hiragana: "うごく", meaning: "움직이다, 작동하다" },
  { kanji: "グラム", hiragana: "", meaning: "그램" },
  { kanji: "特に", hiragana: "とくに", meaning: "특히, 특별히" },
  { kanji: "空く", hiragana: "すく", meaning: "비다, 비어 있다, 열리다, 한가하다" },
  { kanji: "積もる", hiragana: "つもる", meaning: "쌓이다" },
  { kanji: "郵便局", hiragana: "ゆうびんきょく", meaning: "우체국" },
  { kanji: "立派", hiragana: "りっぱ", meaning: "훌륭함" },
  { kanji: "ガラス", hiragana: "", meaning: "유리" },
  { kanji: "祈る", hiragana: "いのる", meaning: "빌다, 기도하다, 기원하다" },
  { kanji: "決まる", hiragana: "きまる", meaning: "정해지다, 결정되다" },
  { kanji: "橋", hiragana: "はし", meaning: "다리, 교랑" },
  { kanji: "大切", hiragana: "たいせつ", meaning: "중요, 귀중, 소중" },
  { kanji: "言葉", hiragana: "ことば", meaning: "말, 언어" },
  { kanji: "ゲーム", hiragana: "", meaning: "게임" },
  { kanji: "捨てる", hiragana: "すてる", meaning: "버리다" },
  { kanji: "電灯", hiragana: "でんとう", meaning: "전등" },
  { kanji: "込む", hiragana: "こむ", meaning: "혼잡하다, 붐비다" },
  { kanji: "金持ち", hiragana: "かねもち", meaning: "부자" },
  { kanji: "スーツ", hiragana: "", meaning: "수트, 양복" },
  { kanji: "きっと", hiragana: "", meaning: "분명, 꼭, 반드시" },
  { kanji: "始まり", hiragana: "はじまり", meaning: "시작, 시초, 기원" },
  { kanji: "戻す", hiragana: "もどす", meaning: "되돌리다" },
  { kanji: "予定", hiragana: "よてい", meaning: "예정" },
  { kanji: "普通", hiragana: "ふつう", meaning: "보통, 대개" },
  { kanji: "合う", hiragana: "あう", meaning: "합쳐지다, 서로 ~하다, 맞다" },
  { kanji: "真面目", hiragana: "まじめ", meaning: "착실함, 성실함, 진지함" },
  { kanji: "文化", hiragana: "ぶんか", meaning: "문화" },
  { kanji: "心", hiragana: "こころ", meaning: "마음" },
  { kanji: "場所", hiragana: "ばしょ", meaning: "장소, 위치" },
  { kanji: "窓口", hiragana: "まどぐち", meaning: "창구" },
  { kanji: "ポスト", hiragana: "", meaning: "우체통, 우편함" },
  { kanji: "焼く", hiragana: "やく", meaning: "굽다, 태우다, 애태우다" },
  { kanji: "晴れ", hiragana: "はれ", meaning: "하늘이 갬, 날씨가 좋음" },
  { kanji: "下さる", hiragana: "くださる", meaning: "주시다" },
  { kanji: "喧嘩", hiragana: "けんか", meaning: "다툼, 싸움" },
  { kanji: "太る", hiragana: "ふとる", meaning: "살찌다" },
  { kanji: "柔道", hiragana: "じゅうどう", meaning: "유도" },
  { kanji: "着る", hiragana: "きる", meaning: "입다" },
  { kanji: "片仮名", hiragana: "かたかな", meaning: "가타카나, 카타카나" },
  { kanji: "試合", hiragana: "しあい", meaning: "시합" },
  { kanji: "日記", hiragana: "にっき", meaning: "일기" },
  { kanji: "反対", hiragana: "はんたい", meaning: "반대" },
  { kanji: "運転", hiragana: "うんてん", meaning: "운전" },
  { kanji: "くれる", hiragana: "", meaning: "주다" },
  { kanji: "他界", hiragana: "たかい", meaning: "타계, 죽음, 인간계 이외의 세계" },
  { kanji: "これから", hiragana: "", meaning: "지금부터, 이제부터, 앞으로" },
  { kanji: "祖父", hiragana: "そふ", meaning: "조부, 할아버지" },
  { kanji: "取る", hiragana: "とる", meaning: "잡다, 들다, 쥐다" },
  { kanji: "止まる", hiragana: "とまる", meaning: "멈추다, 멎다, 그치다, 정지하다, 서다" },
  { kanji: "賛成", hiragana: "さんせい", meaning: "찬성" },
  { kanji: "全体", hiragana: "ぜんたい", meaning: "전체" },
  { kanji: "一々", hiragana: "いちいち", meaning: "일일이, 하나하나" },
  { kanji: "アメリカ", hiragana: "", meaning: "아메리카, 미국" },
  { kanji: "それでは", hiragana: "", meaning: "그러면, 그럼, 그렇다면" },
  { kanji: "正月", hiragana: "しょうがつ", meaning: "정월, 설" },
  { kanji: "指", hiragana: "ゆび", meaning: "손가락" },
  { kanji: "子", hiragana: "こ", meaning: "자식, 아이" },
];
