// lib/words_16_20.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_16_20: Word[] = [
  { kanji: "似合う", hiragana: "にあう", meaning: "잘 맞다, 어울리다, 조화되다" },
  { kanji: "ガソリン", hiragana: "", meaning: "가솔린, 휘발유" },
  { kanji: "プレゼント", hiragana: "", meaning: "선물" },
  { kanji: "血", hiragana: "ち", meaning: "피" },
  { kanji: "アクセサリー", hiragana: "", meaning: "액세서리, 장신구" },
  { kanji: "帰り", hiragana: "かえり", meaning: "돌아옴, 돌아감, 귀가" },
  { kanji: "折れる", hiragana: "おれる", meaning: "접히다, 꺾이다, 부러지다" },
  { kanji: "時", hiragana: "とき", meaning: "시간, 시각, 때" },
  { kanji: "天気予報", hiragana: "てんきよほう", meaning: "일기 예보" },
  { kanji: "カレー", hiragana: "", meaning: "카레" },
  { kanji: "出来る", hiragana: "できる", meaning: "할 수 있다, 할 줄 알다, 가능하다" },
  { kanji: "伝える", hiragana: "つたえる", meaning: "전하다, 전도하다, 전달하다" },
  { kanji: "到頭", hiragana: "とうとう", meaning: "드디어, 결국, 마침내" },
  { kanji: "習慣", hiragana: "しゅうかん", meaning: "습관" },
  { kanji: "羽", hiragana: "はね", meaning: "날개" },
  { kanji: "一体", hiragana: "いったい", meaning: "전반적으로, 대체로, 도대체" },
  { kanji: "曇る", hiragana: "くもる", meaning: "흐리다, 흐려지다, 어두워지다" },
  { kanji: "暮れる", hiragana: "くれる", meaning: "저물다, 해가 지다" },
  { kanji: "用意", hiragana: "ようい", meaning: "준비, 대비" },
  { kanji: "花見", hiragana: "はなみ", meaning: "꽃구경, 꽃놀이" },
  { kanji: "柔らかい", hiragana: "やわらかい", meaning: "말랑하다, 부드럽다" },
  { kanji: "地理", hiragana: "ちり", meaning: "지리" },
  { kanji: "技術", hiragana: "ぎじゅつ", meaning: "기술" },
  { kanji: "理由", hiragana: "りゆう", meaning: "이유" },
  { kanji: "経済", hiragana: "けいざい", meaning: "경제" },
  { kanji: "景色", hiragana: "けしき", meaning: "경치" },
  { kanji: "ピアノ", hiragana: "", meaning: "피아노" },
  { kanji: "割れる", hiragana: "われる", meaning: "깨지다, 갈라지다" },
  { kanji: "向こう", hiragana: "むこう", meaning: "저편, 맞은편, 건너편, 저쪽" },
  { kanji: "恥ずかしい", hiragana: "はずかしい", meaning: "부끄럽다, 창피하다" },
  { kanji: "毛", hiragana: "け", meaning: "털" },
  { kanji: "研究室", hiragana: "けんきゅうしつ", meaning: "연구실" },
  { kanji: "ボート", hiragana: "", meaning: "보트" },
  { kanji: "テキスト", hiragana: "", meaning: "텍스트, 교재" },
  { kanji: "校長", hiragana: "こうちょう", meaning: "교장" },
  { kanji: "見付かる", hiragana: "みつかる", meaning: "발견되다, 들키다" },
  { kanji: "森", hiragana: "もり", meaning: "수풀, 삼림, 숲" },
  { kanji: "サンダル", hiragana: "", meaning: "샌들" },
  { kanji: "番", hiragana: "ばん", meaning: "순서, 차례" },
  { kanji: "週間", hiragana: "しゅうかん", meaning: "주간" },
  { kanji: "泊める", hiragana: "とめる", meaning: "숙박시키다, 묵게 하다, 정박시키다" },
  { kanji: "特別", hiragana: "とくべつ", meaning: "특별" },
  { kanji: "踊り", hiragana: "おどり", meaning: "춤, 무용" },
  { kanji: "講堂", hiragana: "こうどう", meaning: "강당" },
  { kanji: "訪ねる", hiragana: "たずねる", meaning: "찾다, 방문하다" },
  { kanji: "深い", hiragana: "ふかい", meaning: "깊다" },
  { kanji: "国産", hiragana: "こくさん", meaning: "국산" },
  { kanji: "骨", hiragana: "ほね", meaning: "뼈, 뼈대" },
  { kanji: "答え", hiragana: "こたえ", meaning: "대답, 해답" },
  { kanji: "歯医者", hiragana: "はいしゃ", meaning: "치과 의사, 치과" },
  { kanji: "渡す", hiragana: "わたす", meaning: "건네주다, 건너게 하다" },
  { kanji: "布団", hiragana: "ふとん", meaning: "이부자리, 이불" },
  { kanji: "語", hiragana: "ご", meaning: "말, 언어, 단어" },
  { kanji: "頼む", hiragana: "たのむ", meaning: "부탁하다" },
  { kanji: "彼女", hiragana: "かのじょ", meaning: "그녀, 여자친구" },
  { kanji: "経験", hiragana: "けいけん", meaning: "경험" },
  { kanji: "トラック", hiragana: "", meaning: "트럭, 화물 자동차" },
  { kanji: "ガス", hiragana: "", meaning: "가스" },
  { kanji: "テニス", hiragana: "", meaning: "테니스" },
  { kanji: "駄目", hiragana: "だめ", meaning: "소용없음, 못씀, 안됨" },
  { kanji: "葡萄", hiragana: "ぶどう", meaning: "포도" },
  { kanji: "回る", hiragana: "まわる", meaning: "돌다, 회전하다" },
  { kanji: "然し", hiragana: "しかし", meaning: "그러나, 그렇지만, 그런데" },
  { kanji: "聞こえる", hiragana: "きこえる", meaning: "들리다" },
  { kanji: "レポート", hiragana: "", meaning: "레포트, 보고서" },
  { kanji: "並ぶ", hiragana: "ならぶ", meaning: "줄지어 늘어서다, 나란히 서다" },
  { kanji: "月", hiragana: "つき", meaning: "달, 달빛, 한 달, 월" },
  { kanji: "社会", hiragana: "しゃかい", meaning: "사회" },
  { kanji: "女性", hiragana: "じょせい", meaning: "여성" },
  { kanji: "濡れる", hiragana: "ぬれる", meaning: "젖다" },
  { kanji: "台", hiragana: "だい", meaning: "대, 받침대" },
  { kanji: "生きる", hiragana: "いきる", meaning: "살다" },
  { kanji: "九つ", hiragana: "ここのつ", meaning: "아홉개, 9개" },
  { kanji: "乗り物", hiragana: "のりもの", meaning: "탈것, 교통편, 교통 기관" },
  { kanji: "代わり", hiragana: "かわり", meaning: "대리, 대용, 대신" },
];