// lib/words_06_10.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_06_10: Word[] = [
  { kanji: "パージ", hiragana: "", meaning: "추방, 숙청" },
  { kanji: "医学", hiragana: "いがく", meaning: "의학" },
  { kanji: "受付", hiragana: "うけつけ", meaning: "접수처" },
  { kanji: "残念", hiragana: "ざんねん", meaning: "유감스러움, 아쉬움" },
  { kanji: "複雑", hiragana: "ふくざつ", meaning: "복잡" },
  { kanji: "急ぐ", hiragana: "いそぐ", meaning: "서두르다" },
  { kanji: "守る", hiragana: "まもる", meaning: "지키다" },
  { kanji: "大変", hiragana: "たいへん", meaning: "큰일, 정말, 매우" },
  { kanji: "ケーキ", hiragana: "", meaning: "케이크" },
  { kanji: "切る", hiragana: "きる", meaning: "자르다" },
  { kanji: "さす", hiragana: "", meaning: "~시키다, 시키다" },
  { kanji: "鳴く", hiragana: "なく", meaning: "소리를 내다, 울다" },
  { kanji: "ベル", hiragana: "", meaning: "벨, 종, 방울" },
  { kanji: "苦しい", hiragana: "くるしい", meaning: "괴롭다, 고통스럽다" },
  { kanji: "意見", hiragana: "いけん", meaning: "의견" },
  { kanji: "居間", hiragana: "いま", meaning: "거실" },
  { kanji: "真ん中", hiragana: "まんなか", meaning: "한가운데, 한복판" },
  { kanji: "払う", hiragana: "はらう", meaning: "없애다, 제거하다, 털다, 털어 내다, 지불하다, 값을 치르다" },
  { kanji: "フィルム", hiragana: "", meaning: "필름" },
  { kanji: "乗り換える", hiragana: "のりかえる", meaning: "바꿔 타다, 갈아타다, 환승하다" },
  { kanji: "安全", hiragana: "あんぜん", meaning: "안전" },
  { kanji: "喜ぶ", hiragana: "よろこぶ", meaning: "기뻐하다" },
  { kanji: "付ける", hiragana: "つける", meaning: "붙이다, 달다" },
  { kanji: "即ける", hiragana: "つける", meaning: "왕위에 앉히다, 즉위하다" },
  { kanji: "しっかり", hiragana: "", meaning: "단단히, 꽉, 확고히, 제대로" },
  { kanji: "凄い", hiragana: "すごい", meaning: "굉장하다, 대단하다" },
  { kanji: "汽車", hiragana: "きしゃ", meaning: "기차" },
  { kanji: "贈り物", hiragana: "おくりもの", meaning: "선물" },
  { kanji: "人", hiragana: "にん", meaning: "사람, 인품" },
  { kanji: "映画", hiragana: "えいが", meaning: "영화" },
  { kanji: "アイロン", hiragana: "", meaning: "다리미, 헤어 아이롱, 고데기" },
  { kanji: "美しい", hiragana: "うつくしい", meaning: "아름답다, 예쁘다" },
  { kanji: "アルバイト", hiragana: "", meaning: "아르바이트" },
  { kanji: "授業", hiragana: "じゅぎょう", meaning: "수업" },
  { kanji: "届く", hiragana: "とどく", meaning: "닿다, 도달하다, 이루어지다" },
  { kanji: "外部", hiragana: "がいぶ", meaning: "외부" },
  { kanji: "勝つ", hiragana: "かつ", meaning: "이기다" },
  { kanji: "零", hiragana: "れい", meaning: "영, 0" },
  { kanji: "全国", hiragana: "ぜんこく", meaning: "전국" },
  { kanji: "良く", hiragana: "よく", meaning: "잘, 충분히, 좋게" },
  { kanji: "ぶつかる", hiragana: "", meaning: "부딪히다, 충돌하다" },
  { kanji: "謝る", hiragana: "あやまる", meaning: "사과하다" },
  { kanji: "褒める", hiragana: "ほめる", meaning: "칭찬하다" },
  { kanji: "又は", hiragana: "または", meaning: "또는, 혹은, 그게 아니면" },
  { kanji: "沸く", hiragana: "わく", meaning: "끓다, 금속이 녹다, 발효하다" },
  { kanji: "打つ", hiragana: "うつ", meaning: "치다, 때리다, 두드리다" },
  { kanji: "見付ける", hiragana: "みつける", meaning: "찾다, 발견하다" },
  { kanji: "選手", hiragana: "せんしゅ", meaning: "선수" },
  { kanji: "高校", hiragana: "こうこう", meaning: "고교, 고등학교" },
  { kanji: "カーテン", hiragana: "", meaning: "커튼" },
  { kanji: "例えば", hiragana: "たとえば", meaning: "예를 들면, 예컨대, 가령" },
  { kanji: "さあ", hiragana: "", meaning: "자, 어서, 글쎄" },
  { kanji: "釣る", hiragana: "つる", meaning: "낚다, 꾀다, 유혹하다" },
  { kanji: "鏡", hiragana: "かがみ", meaning: "거울" },
  { kanji: "逃げる", hiragana: "にげる", meaning: "도망치다, 달아나다, 회피하다" },
  { kanji: "ニュース", hiragana: "", meaning: "뉴스" },
  { kanji: "この間", hiragana: "このあいだ", meaning: "일전, 요전, 지난번" },
  { kanji: "温い", hiragana: "ぬるい", meaning: "미지근하다, 미적지근하다" },
  { kanji: "退院", hiragana: "たいいん", meaning: "퇴원" },
  { kanji: "流れる", hiragana: "ながれる", meaning: "흐르다, 흘러내리다, 흘러가다" },
  { kanji: "ワンピース", hiragana: "", meaning: "원피스" },
  { kanji: "西洋", hiragana: "せいよう", meaning: "서양" },
  { kanji: "気持ち", hiragana: "きもち", meaning: "마음, 기분, 감정" },
  { kanji: "壊れる", hiragana: "こわれる", meaning: "고장나다, 부서지다, 파괴되다" },
  { kanji: "一緒", hiragana: "いっしょ", meaning: "같이, 함께" },
  { kanji: "光", hiragana: "ひかり", meaning: "빛" },
  { kanji: "手前", hiragana: "てまえ", meaning: "저, 너" },
  { kanji: "公務員", hiragana: "こうむいん", meaning: "공무원" },
  { kanji: "旅館", hiragana: "りょかん", meaning: "여관" },
  { kanji: "途中", hiragana: "とちゅう", meaning: "도중" },
  { kanji: "サラダ", hiragana: "", meaning: "샐러드" },
  { kanji: "申す", hiragana: "もうす", meaning: "말씀하다" },
  { kanji: "機械", hiragana: "きかい", meaning: "기계" },
  { kanji: "引っ越す", hiragana: "ひっこす", meaning: "이사하다" },
  { kanji: "けれども", hiragana: "", meaning: "~지만, 그러나, 그렇지만" },
];