// lib/words_36_40.ts

export type Word = {
  kanji: string;
  hiragana: string;
  meaning: string;
};

export const words_36_40: Word[] = [
  { kanji: "彼", hiragana: "かれ", meaning: "그, 그 남자" },
  { kanji: "髪", hiragana: "かみ", meaning: "머리카락" },
  { kanji: "戻る", hiragana: "もどる", meaning: "되돌아오다, 되돌아가다" },
  { kanji: "計画", hiragana: "けいかく", meaning: "계획" },
  { kanji: "連れる", hiragana: "つれる", meaning: "데려오다, 데려가다" },
  { kanji: "封筒", hiragana: "ふうとう", meaning: "봉투" },
  { kanji: "今度", hiragana: "こんど", meaning: "이번, 이 다음, 다음" },
  { kanji: "怒る", hiragana: "おこる", meaning: "성내다, 화내다" },
  { kanji: "戦争", hiragana: "せんそう", meaning: "전쟁" },
  { kanji: "付く", hiragana: "つく", meaning: "붙다, 달라붙다, 매달리다" },
  { kanji: "案内", hiragana: "あんない", meaning: "안내" },
  { kanji: "草", hiragana: "くさ", meaning: "풀, 풀밭" },
  { kanji: "アナウンサー", hiragana: "", meaning: "아나운서" },
  { kanji: "裏", hiragana: "うら", meaning: "뒤, 뒷면, 뒤쪽" },
  { kanji: "足りる", hiragana: "たりる", meaning: "족하다, 충분하다" },
  { kanji: "教育", hiragana: "きょういく", meaning: "교육" },
  { kanji: "講義", hiragana: "こうぎ", meaning: "강의" },
  { kanji: "そろそろ", hiragana: "", meaning: "슬슬" },
  { kanji: "男性", hiragana: "だんせい", meaning: "남성" },
  { kanji: "あれ", hiragana: "", meaning: "저것" },
  { kanji: "一度", hiragana: "いちど", meaning: "한번, 일회, 한차례" },
  { kanji: "遊び", hiragana: "あそび", meaning: "놀이, 놀기" },
  { kanji: "メートル", hiragana: "", meaning: "미터" },
  { kanji: "美味い", hiragana: "うまい", meaning: "맛있다" },
  { kanji: "それで", hiragana: "", meaning: "그래서, 그런 까닭에, 그로 인해서" },
  { kanji: "席", hiragana: "せき", meaning: "자리, 좌석" },
  { kanji: "出掛ける", hiragana: "でかける", meaning: "외출하다, 나가다" },
  { kanji: "夜間", hiragana: "やかん", meaning: "야간" },
  { kanji: "今夜", hiragana: "こんや", meaning: "오늘 밤" },
  { kanji: "国立", hiragana: "こくりつ", meaning: "국립" },
  { kanji: "引き出し", hiragana: "ひきだし", meaning: "서랍, 인출" },
  { kanji: "屋", hiragana: "や", meaning: "가게" },
  { kanji: "大体", hiragana: "だいたい", meaning: "대체, 대개, 대강" },
  { kanji: "太い", hiragana: "ふとい", meaning: "굵다" },
  { kanji: "なるべく", hiragana: "", meaning: "될 수 있는 한, 가능한 한, 되도록" },
  { kanji: "致す", hiragana: "いたす", meaning: "하다, 가져오다, 일으키다" },
  { kanji: "弾く", hiragana: "ひく", meaning: "악기를 연주하다, 치다, 켜다" },
  { kanji: "泣く", hiragana: "なく", meaning: "울다" },
  { kanji: "投げる", hiragana: "なげる", meaning: "던지다" },
  { kanji: "規則", hiragana: "きそく", meaning: "규칙" },
  { kanji: "マスク", hiragana: "", meaning: "마스크" },
  { kanji: "自動", hiragana: "じどう", meaning: "자동" },
  { kanji: "失礼", hiragana: "しつれい", meaning: "실례" },
  { kanji: "親しい", hiragana: "したしい", meaning: "친하다, 사이좋다, 가깝다" },
  { kanji: "支度", hiragana: "したく", meaning: "준비, 채비" },
  { kanji: "選ぶ", hiragana: "えらぶ", meaning: "고르다, 선택하다, 택하다" },
  { kanji: "ボール", hiragana: "", meaning: "볼, 공" },
  { kanji: "郊外", hiragana: "こうがい", meaning: "교외" },
  { kanji: "そうして", hiragana: "", meaning: "그리고, 그러고 나서, 그리하여" },
  { kanji: "中止", hiragana: "ちゅうし", meaning: "중지" },
  { kanji: "内部", hiragana: "ないぶ", meaning: "내부" },
  { kanji: "水道", hiragana: "すいどう", meaning: "수도, 상수도" },
  { kanji: "返事", hiragana: "へんじ", meaning: "대답, 답장" },
  { kanji: "留守", hiragana: "るす", meaning: "부재중" },
  { kanji: "空気", hiragana: "くうき", meaning: "공기, 분위기" },
  { kanji: "洗濯", hiragana: "せんたく", meaning: "세탁, 빨래" },
  { kanji: "並べる", hiragana: "ならべる", meaning: "늘어놓다, 나란히 하다, 견주다" },
  { kanji: "滑る", hiragana: "すべる", meaning: "미끄러지다" },
  { kanji: "頂く", hiragana: "いただく", meaning: "받다" },
  { kanji: "港", hiragana: "みなと", meaning: "항구" },
  { kanji: "アジア", hiragana: "", meaning: "아시아" },
  { kanji: "押入れ", hiragana: "おしいれ", meaning: "벽장" },
  { kanji: "ずっと", hiragana: "", meaning: "훨씬, 쭉, 계속" },
  { kanji: "思い出す", hiragana: "おもいだす", meaning: "생각해 내다, 생각나다, 떠올리다" },
  { kanji: "比べる", hiragana: "くらべる", meaning: "비교하다, 대조하다, 경쟁하다" },
  { kanji: "ドレス", hiragana: "", meaning: "드레스" },
  { kanji: "勤める", hiragana: "つとめる", meaning: "종사하다, 근무하다" },
  { kanji: "値段", hiragana: "ねだん", meaning: "값, 가격" },
  { kanji: "仰る", hiragana: "おっしゃる", meaning: "말씀하시다" },
  { kanji: "半分", hiragana: "はんぶん", meaning: "반, 절반" },
  { kanji: "触る", hiragana: "さわる", meaning: "닿다, 손을 대다, 만지다" },
  { kanji: "手袋", hiragana: "てぶくろ", meaning: "장갑" },
  { kanji: "ページ", hiragana: "", meaning: "페이지" },
  { kanji: "叱る", hiragana: "しかる", meaning: "꾸짖다, 야단치다, 혼내다" },
  { kanji: "続く", hiragana: "つづく", meaning: "계속되다, 지속되다, 연달다, 잇따르다, 이어지다" },
];